import { insert, Random } from '../random.js';
import type { Scenario } from '../scenario.js';
import { fullNames } from './names.js';

const schema = `
create table aeroportos (
  id integer generated by default as identity primary key,
  sigla text not null unique,
  cidade text not null
);

create table voos (
  id integer generated by default as identity primary key,
  numero text not null,
  origem_id integer not null references aeroportos (id),
  destino_id integer not null references aeroportos (id) check (destino_id <> origem_id),
  partida timestamp not null,
  chegada timestamp not null check (chegada > partida)
);

create table reservas (
  id integer generated by default as identity primary key,
  voo_id integer not null references voos (id),
  passageiro text not null,
  preco numeric(10, 2) not null check (preco > 0),
  status text not null check (status in ('confirmada', 'cancelada'))
);`;

const aeroportos: readonly [sigla: string, cidade: string][] = [
  ['GRU', 'São Paulo'],
  ['GIG', 'Rio de Janeiro'],
  ['CNF', 'Belo Horizonte'],
  ['SSA', 'Salvador'],
  ['REC', 'Recife'],
  ['POA', 'Porto Alegre'],
  ['CWB', 'Curitiba'],
  ['MAO', 'Manaus'],
];

function seed(variant: number): string {
  const random = new Random(6_000 + variant * 3_202_591);
  const pick = <T>(items: readonly T[]) => random.pick(items);

  // One airport with no outbound flight: the "never an origin" challenge needs it.
  const origins = aeroportos.slice(0, aeroportos.length - 1);

  const voos = Array.from({ length: 22 }, (_, i) => {
    const origemIdx = origins.indexOf(pick(origins));
    let destinoIdx = random.int(0, aeroportos.length - 1);
    while (destinoIdx === origemIdx) destinoIdx = random.int(0, aeroportos.length - 1);

    const dia = 1 + random.int(0, 27);
    const horaPartida = random.int(5, 20);
    const duracaoMin = random.int(45, 240);
    const partida = `2026-02-${String(dia).padStart(2, '0')} ${String(horaPartida).padStart(2, '0')}:${String(random.int(0, 3) * 15).padStart(2, '0')}:00`;
    const chegadaDate = new Date(`${partida.replace(' ', 'T')}Z`);
    chegadaDate.setUTCMinutes(chegadaDate.getUTCMinutes() + duracaoMin);
    const chegada = chegadaDate.toISOString().slice(0, 19).replace('T', ' ');

    return {
      id: i + 1,
      numero: `LB${1000 + i}`,
      origemId: origemIdx + 1,
      destinoId: destinoIdx + 1,
      partida,
      chegada,
    };
  });

  // Guarantee at least one flight into Salvador, so that challenge always has an answer.
  const salvadorId = aeroportos.findIndex(([, cidade]) => cidade === 'Salvador') + 1;
  voos[0]!.destinoId = salvadorId;
  if (voos[0]!.origemId === salvadorId) voos[0]!.origemId = (salvadorId % aeroportos.length) + 1;

  // Three flights never get a confirmed booking: the "no confirmed booking" challenge needs them.
  const bookable = voos.slice(0, voos.length - 3);

  const reservas: { vooId: number; passageiro: string; preco: number; status: string }[] = [];
  for (const voo of bookable) {
    const nomes = fullNames(pick, random.int(1, 4));
    for (const nome of nomes) {
      const status = random.next() < 0.85 ? 'confirmada' : 'cancelada';
      reservas.push({
        vooId: voo.id,
        passageiro: nome,
        preco: Math.round((280 + random.next() * 1_400) * 100) / 100,
        status,
      });
    }
  }
  // Guarantee at least one cancelled booking, so that challenge has something to find.
  reservas[0]!.status = 'cancelada';

  return [
    insert(
      'aeroportos',
      ['id', 'sigla', 'cidade'],
      aeroportos.map(([sigla, cidade], i) => [i + 1, sigla, cidade]),
    ),
    insert(
      'voos',
      ['id', 'numero', 'origem_id', 'destino_id', 'partida', 'chegada'],
      voos.map((v) => [v.id, v.numero, v.origemId, v.destinoId, v.partida, v.chegada]),
    ),
    insert(
      'reservas',
      ['voo_id', 'passageiro', 'preco', 'status'],
      reservas.map((r) => [r.vooId, r.passageiro, r.preco.toFixed(2), r.status]),
    ),
    `select setval(pg_get_serial_sequence('aeroportos', 'id'), ${aeroportos.length}),
            setval(pg_get_serial_sequence('voos', 'id'), ${voos.length}),
            setval(pg_get_serial_sequence('reservas', 'id'), ${Math.max(reservas.length, 1)});`,
  ].join('\n\n');
}

export const aeroporto: Scenario = {
  id: 'aeroporto',
  title: 'Aeroporto',
  summary: 'Aeroportos, voos e reservas de passagens de uma companhia aérea regional.',
  level: 'intermediário',
  schema,
  seed,
  starter: `-- Explore os dados. Ctrl+Enter executa.
select v.numero, o.cidade as origem, d.cidade as destino, v.partida
from voos v
join aeroportos o on o.id = v.origem_id
join aeroportos d on d.id = v.destino_id
order by v.partida
limit 10;`,
  challenges: [
    {
      id: 'voos-para-cidade',
      title: 'Voos para uma cidade',
      prompt: 'Liste o número dos voos com destino a Salvador.',
      hint: 'Junte voos com aeroportos usando destino_id, e filtre pela cidade desse aeroporto.',
      concept: {
        text: 'Um JOIN pode ligar a mesma tabela duas vezes na mesma consulta, uma para cada papel (aqui, origem e destino) — mas para uma pergunta que só depende do destino, basta juntar uma vez.',
        url: 'https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-JOIN',
      },
      solution: `select v.numero
from voos v
join aeroportos d on d.id = v.destino_id
where d.cidade = 'Salvador'`,
      ordered: false,
    },
    {
      id: 'canceladas',
      title: 'Reservas canceladas',
      prompt: 'Liste o nome do passageiro e o número do voo das reservas com status cancelada.',
      concept: {
        text: 'A cláusula WHERE filtra linhas com uma condição booleana, avaliada por linha antes de o resultado ser montado.',
        url: 'https://www.postgresql.org/docs/current/sql-select.html#SQL-WHERE',
      },
      solution: `select r.passageiro, v.numero
from reservas r
join voos v on v.id = r.voo_id
where r.status = 'cancelada'`,
      ordered: false,
    },
    {
      id: 'duracao',
      title: 'Duração de cada voo',
      prompt:
        'Mostre o número de cada voo e sua duração (chegada menos partida), do voo mais longo para o mais curto.',
      hint: 'Subtrair um timestamp de outro produz um INTERVAL.',
      concept: {
        text: 'Subtrair dois valores timestamp produz um INTERVAL, um período de tempo — que pode ser comparado e ordenado como qualquer outro valor.',
        url: 'https://www.postgresql.org/docs/current/functions-datetime.html',
      },
      solution: `select numero, chegada - partida as duracao
from voos
order by duracao desc`,
      ordered: true,
    },
    {
      id: 'receita-confirmada',
      title: 'Receita confirmada por voo',
      prompt:
        'Para cada voo que tem pelo menos uma reserva confirmada, mostre o número dele e a soma dos preços das reservas confirmadas.',
      hint: 'Filtre por status antes de agrupar — WHERE, não HAVING, já que a condição é sobre a linha, não sobre o grupo.',
      concept: {
        text: 'GROUP BY reúne as linhas por voo antes da agregação. Uma condição sobre colunas da própria linha, como o status da reserva, se filtra com WHERE antes do agrupamento — não com HAVING.',
        url: 'https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-GROUP',
      },
      solution: `select v.numero, sum(r.preco) as receita
from reservas r
join voos v on v.id = r.voo_id
where r.status = 'confirmada'
group by v.id, v.numero`,
      ordered: false,
    },
    {
      id: 'sem-reserva-confirmada',
      title: 'Voos sem nenhuma reserva confirmada',
      prompt: 'Liste o número dos voos que não têm nenhuma reserva com status confirmada.',
      hint: 'NOT EXISTS com a condição de status dentro da subconsulta correlacionada.',
      concept: {
        text: 'NOT EXISTS testa a ausência de qualquer linha que satisfaça uma subconsulta correlacionada — a condição de status entra dentro da subconsulta, não do lado de fora.',
        url: 'https://www.postgresql.org/docs/current/functions-subquery.html#FUNCTIONS-SUBQUERY-EXISTS',
      },
      solution: `select numero from voos v
where not exists (
  select 1 from reservas r where r.voo_id = v.id and r.status = 'confirmada'
)`,
      ordered: false,
    },
    {
      id: 'nunca-origem',
      title: 'Aeroportos que nunca são origem',
      prompt: 'Liste a cidade dos aeroportos que nunca aparecem como origem de um voo.',
      concept: {
        text: 'NOT EXISTS testa a ausência de qualquer linha que satisfaça uma subconsulta correlacionada — a forma direta de expressar "para o qual não existe".',
        url: 'https://www.postgresql.org/docs/current/functions-subquery.html#FUNCTIONS-SUBQUERY-EXISTS',
      },
      solution: `select cidade from aeroportos a
where not exists (select 1 from voos v where v.origem_id = a.id)`,
      ordered: false,
    },
  ],
};
