import { insert, Random } from '../random.js';
import type { Scenario } from '../scenario.js';
import { addDays, fullNames } from './names.js';

const schema = `
create table contas (
  id integer generated by default as identity primary key,
  titular text not null,
  tipo text not null check (tipo in ('corrente', 'poupança')),
  aberta_em date not null
);

create table transacoes (
  id integer generated by default as identity primary key,
  conta_id integer not null references contas (id),
  ocorrida_em timestamp not null,
  tipo text not null check (tipo in ('deposito', 'saque')),
  valor numeric(10, 2) not null check (valor > 0)
);`;

function seed(variant: number): string {
  const random = new Random(9_000 + variant * 5_336_129);
  const pick = <T>(items: readonly T[]) => random.pick(items);

  const contas = fullNames(pick, 10).map((titular, i) => ({
    id: i + 1,
    titular,
    tipo: random.next() < 0.7 ? 'corrente' : 'poupança',
    abertaEm: addDays('2023-01-01', random.int(0, 900)),
  }));

  const transacoes: {
    id: number;
    contaId: number;
    ocorridaEm: string;
    tipo: 'deposito' | 'saque';
    valor: number;
  }[] = [];
  let id = 1;

  for (const conta of contas) {
    // An opening deposit first, so a running balance never has to consider "no history yet".
    const numMovs = random.int(5, 9);
    let minuto = 0;
    transacoes.push({
      id: id++,
      contaId: conta.id,
      ocorridaEm: `${addDays(conta.abertaEm, 0)} 09:00:00`,
      tipo: 'deposito',
      valor: Math.round((800 + random.next() * 1_200) * 100) / 100,
    });
    for (let m = 0; m < numMovs; m++) {
      minuto += random.int(1, 5);
      const dia = addDays(conta.abertaEm, random.int(1, 200));
      transacoes.push({
        id: id++,
        contaId: conta.id,
        ocorridaEm: `${dia} ${String(8 + (minuto % 10)).padStart(2, '0')}:${String((minuto * 11) % 60).padStart(2, '0')}:00`,
        tipo: random.next() < 0.55 ? 'saque' : 'deposito',
        valor: Math.round((40 + random.next() * 600) * 100) / 100,
      });
    }
  }

  return [
    insert(
      'contas',
      ['id', 'titular', 'tipo', 'aberta_em'],
      contas.map((c) => [c.id, c.titular, c.tipo, c.abertaEm]),
    ),
    insert(
      'transacoes',
      ['id', 'conta_id', 'ocorrida_em', 'tipo', 'valor'],
      transacoes.map((t) => [t.id, t.contaId, t.ocorridaEm, t.tipo, t.valor.toFixed(2)]),
    ),
    `select setval(pg_get_serial_sequence('contas', 'id'), ${contas.length}),
            setval(pg_get_serial_sequence('transacoes', 'id'), ${transacoes.length});`,
  ].join('\n\n');
}

export const banco: Scenario = {
  id: 'banco',
  title: 'Banco',
  summary: 'Contas e transações (depósitos e saques) de uma pequena instituição financeira.',
  level: 'avançado',
  schema,
  seed,
  starter: `-- Explore os dados. Ctrl+Enter executa.
select c.titular, t.ocorrida_em, t.tipo, t.valor
from transacoes t
join contas c on c.id = t.conta_id
order by t.ocorrida_em
limit 10;`,
  challenges: [
    {
      id: 'saldo-atual',
      title: 'Saldo atual de cada conta',
      prompt:
        'Mostre o titular de cada conta e o saldo atual dela: soma dos depósitos menos a soma dos saques.',
      hint: 'CASE WHEN dentro do SUM transforma cada linha num valor positivo ou negativo antes de somar.',
      concept: {
        text: 'Uma expressão CASE pode ficar dentro de uma função de agregação: aqui, ela decide se o valor de cada linha entra somado ou subtraído, o que evita duas subconsultas separadas para depósitos e saques.',
        url: 'https://www.postgresql.org/docs/current/functions-conditional.html#FUNCTIONS-CASE',
      },
      solution: `select c.titular,
  sum(case when t.tipo = 'deposito' then t.valor else -t.valor end) as saldo
from contas c
join transacoes t on t.conta_id = c.id
group by c.id, c.titular`,
      ordered: false,
    },
    {
      id: 'saldo-corrido',
      title: 'Saldo corrido de cada conta',
      prompt:
        'Para cada transação, mostre o titular da conta, a data (ocorrida_em) e o saldo acumulado da conta até aquele momento, inclusive. Ordene por conta e, dentro dela, pela data (em caso de empate, pelo id da transação).',
      hint: 'Some o valor com sinal (positivo para depósito, negativo para saque) com uma função de janela acumulada, particionada por conta.',
      concept: {
        text: 'SUM(expr) OVER (PARTITION BY ... ORDER BY ...) acumula expr dentro de cada partição, na ordem da janela — uma soma corrida por grupo, sem precisar de uma subconsulta correlacionada.',
        url: 'https://www.postgresql.org/docs/current/functions-window.html',
      },
      solution: `select c.titular, t.ocorrida_em,
  sum(case when t.tipo = 'deposito' then t.valor else -t.valor end)
    over (partition by t.conta_id order by t.ocorrida_em, t.id) as saldo
from contas c
join transacoes t on t.conta_id = c.id
order by c.id, t.ocorrida_em, t.id`,
      ordered: true,
    },
    {
      id: 'ultimas-tres',
      title: 'As três transações mais recentes de cada conta',
      prompt:
        'Para cada conta, mostre o titular e a data das três transações mais recentes dela (a mais nova primeiro). Contas com menos de três transações mostram todas as que existirem.',
      hint: 'Uma subconsulta LATERAL, para cada linha de contas, roda de novo — com LIMIT — filtrando pela conta da linha externa.',
      concept: {
        text: 'LATERAL permite que uma subconsulta na cláusula FROM referencie colunas de tabelas anteriores na mesma consulta — o que possibilita, com LIMIT dentro dela, pegar "as N mais recentes de cada grupo" sem funções de janela.',
        url: 'https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-LATERAL',
      },
      solution: `select c.titular, t.ocorrida_em
from contas c
join lateral (
  select ocorrida_em from transacoes tt
  where tt.conta_id = c.id
  order by tt.ocorrida_em desc
  limit 3
) t on true
order by c.titular, t.ocorrida_em desc`,
      ordered: true,
    },
    {
      id: 'ficaram-negativas',
      title: 'Contas que já ficaram negativas',
      prompt: 'Liste o titular das contas cujo saldo acumulado ficou negativo em algum momento.',
      hint: 'Calcule o saldo corrido numa CTE e filtre, na consulta de fora, quem teve algum valor abaixo de zero.',
      concept: {
        text: 'Uma CTE (WITH) nomeia o resultado de uma consulta para reutilizá-lo depois — útil quando o filtro final depende de um valor calculado por linha, como um saldo corrido, que não pode ser testado direto no WHERE.',
        url: 'https://www.postgresql.org/docs/current/queries-with.html',
      },
      solution: `with saldo_corrido as (
  select conta_id,
    sum(case when tipo = 'deposito' then valor else -valor end)
      over (partition by conta_id order by ocorrida_em, id) as saldo
  from transacoes
)
select distinct c.titular
from contas c
join saldo_corrido s on s.conta_id = c.id
where s.saldo < 0`,
      ordered: false,
    },
  ],
};
