import { insert, Random } from '../random.js';
import type { Scenario } from '../scenario.js';
import { addDays, fullNames } from './names.js';

const schema = `
create table pacientes (
  id integer generated by default as identity primary key,
  nome text not null,
  data_nascimento date not null
);

create table medicos (
  id integer generated by default as identity primary key,
  nome text not null,
  especialidade text not null
);

create table consultas (
  id integer generated by default as identity primary key,
  paciente_id integer not null references pacientes (id),
  medico_id integer not null references medicos (id),
  agendada_para timestamp not null,
  status text not null check (status in ('agendada', 'realizada', 'cancelada'))
);`;

const especialidades = ['Clínica Geral', 'Pediatria', 'Cardiologia', 'Dermatologia'] as const;

/** "Hoje" para o desafio de faixa etária. Fixo, para a resposta não depender do relógio. */
const TODAY = '2026-03-01';

function seed(variant: number): string {
  const random = new Random(5_000 + variant * 6_700_417);
  const pick = <T>(items: readonly T[]) => random.pick(items);

  const pacientes = fullNames(pick, 14).map((name, i) => ({
    id: i + 1,
    nome: name,
    // From newborns to the elderly, spread over a wide range of birth years.
    dataNascimento: addDays('1945-01-01', random.int(0, 29_000)),
  }));

  const medicos = fullNames(pick, 6).map((name, i) => ({
    id: i + 1,
    nome: name,
    especialidade: especialidades[i % especialidades.length]!,
  }));

  // One doctor never has a completed appointment: the "no completed visits" challenge needs it.
  const activeDoctors = medicos.slice(0, medicos.length - 1);

  // Distinct minutes across the whole clinic: DISTINCT ON needs one clear latest appointment.
  const slots = random.sample(
    Array.from({ length: 2_000 }, (_, i) => i),
    40,
  );

  const consultas = slots.map((slot, i) => {
    const paciente = pick(pacientes);
    const status = random.next();
    return {
      id: i + 1,
      pacienteId: paciente.id,
      medicoId: pick(activeDoctors).id,
      agendadaPara: `${addDays('2026-01-01', Math.floor(slot / 20))} ${String(8 + (slot % 10)).padStart(2, '0')}:${String((slot * 7) % 60).padStart(2, '0')}:00`,
      status: status < 0.15 ? 'cancelada' : status < 0.55 ? 'agendada' : 'realizada',
    } as const;
  });

  return [
    insert(
      'pacientes',
      ['id', 'nome', 'data_nascimento'],
      pacientes.map((p) => [p.id, p.nome, p.dataNascimento]),
    ),
    insert(
      'medicos',
      ['id', 'nome', 'especialidade'],
      medicos.map((m) => [m.id, m.nome, m.especialidade]),
    ),
    insert(
      'consultas',
      ['id', 'paciente_id', 'medico_id', 'agendada_para', 'status'],
      consultas.map((c) => [c.id, c.pacienteId, c.medicoId, c.agendadaPara, c.status]),
    ),
    `select setval(pg_get_serial_sequence('pacientes', 'id'), ${pacientes.length}),
            setval(pg_get_serial_sequence('medicos', 'id'), ${medicos.length}),
            setval(pg_get_serial_sequence('consultas', 'id'), ${consultas.length});`,
  ].join('\n\n');
}

export const clinica: Scenario = {
  id: 'clinica',
  title: 'Clínica',
  summary: 'Pacientes, médicos e consultas de uma clínica com várias especialidades.',
  level: 'intermediário',
  schema,
  seed,
  starter: `-- Explore os dados. Ctrl+Enter executa.
select p.nome as paciente, m.nome as medico, c.agendada_para, c.status
from consultas c
join pacientes p on p.id = c.paciente_id
join medicos m on m.id = c.medico_id
order by c.agendada_para
limit 10;`,
  challenges: [
    {
      id: 'especialidade',
      title: 'Médicos de uma especialidade',
      prompt: 'Liste o nome dos médicos de Cardiologia.',
      concept: {
        text: 'A cláusula WHERE filtra linhas com uma condição booleana, avaliada por linha antes de o resultado ser montado.',
        url: 'https://www.postgresql.org/docs/current/sql-select.html#SQL-WHERE',
      },
      solution: "select nome from medicos where especialidade = 'Cardiologia'",
      ordered: false,
    },
    {
      id: 'canceladas',
      title: 'Consultas canceladas',
      prompt: 'Liste o nome do paciente e a data agendada das consultas com status cancelada.',
      concept: {
        text: 'Comparar uma coluna com um valor exato (=) é o filtro mais comum de WHERE; aqui o valor vem de um domínio fixo, garantido pelo CHECK da coluna status.',
        url: 'https://www.postgresql.org/docs/current/sql-select.html#SQL-WHERE',
      },
      solution: `select p.nome, c.agendada_para
from consultas c
join pacientes p on p.id = c.paciente_id
where c.status = 'cancelada'`,
      ordered: false,
    },
    {
      id: 'ultima-consulta',
      title: 'Última consulta de cada paciente',
      prompt:
        'Para cada paciente que tem pelo menos uma consulta, mostre o nome dele e a data da consulta mais recente (agendada_para, o maior valor).',
      hint: 'DISTINCT ON mantém a primeira linha de cada grupo, segundo o ORDER BY — não confunda com DISTINCT sozinho, que olha a linha inteira.',
      concept: {
        text: 'DISTINCT ON (expr) mantém apenas a primeira linha de cada valor de expr, na ordem definida pelo ORDER BY — que precisa começar pela mesma expressão. É um recurso específico do PostgreSQL.',
        url: 'https://www.postgresql.org/docs/current/sql-select.html#SQL-DISTINCT',
      },
      solution: `select distinct on (p.id) p.nome, c.agendada_para
from pacientes p
join consultas c on c.paciente_id = p.id
order by p.id, c.agendada_para desc`,
      ordered: false,
    },
    {
      id: 'varios-medicos',
      title: 'Pacientes com mais de um médico',
      prompt:
        'Liste o nome dos pacientes que já tiveram consultas (de qualquer status) com mais de um médico diferente.',
      hint: 'COUNT(DISTINCT coluna) conta valores diferentes, não linhas.',
      concept: {
        text: 'COUNT(DISTINCT expr) conta quantos valores diferentes de expr aparecem no grupo, em vez de quantas linhas — a diferença importa quando a mesma combinação se repete.',
        url: 'https://www.postgresql.org/docs/current/functions-aggregate.html',
      },
      solution: `select p.nome
from pacientes p
join consultas c on c.paciente_id = p.id
group by p.id, p.nome
having count(distinct c.medico_id) > 1`,
      ordered: false,
    },
    {
      id: 'faixa-etaria',
      title: 'Pacientes por faixa etária',
      prompt: `Considerando hoje como ${TODAY}, conte quantos pacientes têm menos de 18 anos, quantos têm de 18 a 59, e quantos têm 60 ou mais. Mostre três linhas: a faixa (como texto: 'menor de idade', 'adulto' ou 'idoso') e a contagem.`,
      hint: 'AGE calcula um intervalo; EXTRACT(YEAR FROM ...) tira a quantidade de anos completos dele. CASE escolhe o rótulo de cada linha antes do GROUP BY.',
      concept: {
        text: 'Uma expressão CASE pode aparecer em qualquer lugar onde um valor é esperado, inclusive na lista de SELECT ou no GROUP BY — aqui ela transforma uma idade numérica numa categoria de texto antes de agrupar por ela.',
        url: 'https://www.postgresql.org/docs/current/functions-conditional.html#FUNCTIONS-CASE',
      },
      solution: `select case
    when extract(year from age(date '${TODAY}', data_nascimento)) < 18 then 'menor de idade'
    when extract(year from age(date '${TODAY}', data_nascimento)) < 60 then 'adulto'
    else 'idoso'
  end as faixa,
  count(*)
from pacientes
group by faixa`,
      ordered: false,
    },
    {
      id: 'sem-consulta-realizada',
      title: 'Médicos sem nenhum atendimento concluído',
      prompt: 'Liste o nome dos médicos que nunca tiveram uma consulta com status realizada.',
      hint: 'NOT EXISTS com a condição de status dentro da subconsulta correlacionada.',
      concept: {
        text: 'NOT EXISTS testa a ausência de qualquer linha que satisfaça uma subconsulta correlacionada — a condição de status entra dentro da subconsulta, não do lado de fora.',
        url: 'https://www.postgresql.org/docs/current/functions-subquery.html#FUNCTIONS-SUBQUERY-EXISTS',
      },
      solution: `select nome from medicos m
where not exists (
  select 1 from consultas c where c.medico_id = m.id and c.status = 'realizada'
)`,
      ordered: false,
    },
  ],
};
