import { insert, Random } from '../random.js';
import type { Scenario } from '../scenario.js';
import { cities, fullNames } from './names.js';

const schema = `
create table alunos (
  id integer generated by default as identity primary key,
  nome text not null,
  cidade text not null
);

create table disciplinas (
  id integer generated by default as identity primary key,
  nome text not null,
  carga_horaria integer not null check (carga_horaria > 0)
);

create table matriculas (
  id integer generated by default as identity primary key,
  aluno_id integer not null references alunos (id),
  disciplina_id integer not null references disciplinas (id),
  nota numeric(4, 1) check (nota between 0 and 10),
  situacao text not null check (situacao in ('cursando', 'aprovado', 'reprovado')),
  unique (aluno_id, disciplina_id)
);`;

const disciplinas: readonly [name: string, carga: number][] = [
  ['Matemática', 80],
  ['Português', 80],
  ['História', 60],
  ['Geografia', 60],
  ['Ciências', 60],
  ['Inglês', 40],
  ['Educação Física', 40],
  ['Artes', 40],
];

function seed(variant: number): string {
  const random = new Random(3_000 + variant * 15_485_863);
  const pick = <T>(items: readonly T[]) => random.pick(items);

  const alunos = fullNames(pick, 16).map((name, i) => ({
    id: i + 1,
    nome: name,
    cidade: pick(cities),
  }));

  // Load moves a little from variant to variant, so "carga horária alta" is never memorised.
  const disciplinasVariante = disciplinas.map(
    ([nome, carga]) => [nome, carga + random.int(-8, 8)] as const,
  );

  // Two students never enroll: the "students with no enrollment" challenge needs them.
  const enrolled = random.sample(alunos, alunos.length - 2);

  const matriculas: {
    alunoId: number;
    disciplinaId: number;
    nota: number | null;
    situacao: 'cursando' | 'aprovado' | 'reprovado';
  }[] = [];
  let id = 0;
  for (const aluno of enrolled) {
    const suas = random.sample(disciplinasVariante, random.int(3, disciplinasVariante.length));
    for (const [i] of suas.entries()) {
      const disciplinaId = disciplinasVariante.indexOf(suas[i]!) + 1;
      const status = random.next();
      const situacao = status < 0.15 ? 'cursando' : status < 0.55 ? 'aprovado' : 'reprovado';
      // Grades move with the variant, and are null while still in progress.
      const nota =
        situacao === 'cursando'
          ? null
          : Math.round((situacao === 'aprovado' ? 6 + random.next() * 4 : random.next() * 6) * 10) /
            10;
      matriculas.push({ alunoId: aluno.id, disciplinaId, nota, situacao });
      id += 1;
    }
  }

  return [
    insert(
      'alunos',
      ['id', 'nome', 'cidade'],
      alunos.map((a) => [a.id, a.nome, a.cidade]),
    ),
    insert(
      'disciplinas',
      ['id', 'nome', 'carga_horaria'],
      disciplinasVariante.map(([nome, carga], i) => [i + 1, nome, carga]),
    ),
    insert(
      'matriculas',
      ['aluno_id', 'disciplina_id', 'nota', 'situacao'],
      matriculas.map((m) => [m.alunoId, m.disciplinaId, m.nota, m.situacao]),
    ),
    `select setval(pg_get_serial_sequence('alunos', 'id'), ${alunos.length}),
            setval(pg_get_serial_sequence('disciplinas', 'id'), ${disciplinas.length}),
            setval(pg_get_serial_sequence('matriculas', 'id'), ${Math.max(id, 1)});`,
  ].join('\n\n');
}

export const escola: Scenario = {
  id: 'escola',
  title: 'Escola',
  summary: 'Alunos, disciplinas e matrículas de uma escola de ensino fundamental.',
  level: 'iniciante',
  schema,
  seed,
  starter: `-- Explore os dados. Ctrl+Enter executa.
select a.nome, d.nome as disciplina, m.nota, m.situacao
from matriculas m
join alunos a on a.id = m.aluno_id
join disciplinas d on d.id = m.disciplina_id
order by a.nome
limit 10;`,
  challenges: [
    {
      id: 'alunos',
      title: 'Todos os alunos',
      prompt: 'Liste o nome e a cidade de todos os alunos.',
      concept: {
        text: 'A lista de seleção do SELECT escolhe quais colunas aparecem no resultado, na ordem em que você as escreve.',
        url: 'https://www.postgresql.org/docs/current/sql-select.html#SQL-SELECT-LIST',
      },
      solution: 'select nome, cidade from alunos',
      ordered: false,
    },
    {
      id: 'disciplinas-longas',
      title: 'Disciplinas de carga alta',
      prompt: 'Liste o nome das disciplinas com carga horária de 60 horas ou mais.',
      hint: 'Filtre linhas com WHERE.',
      concept: {
        text: 'A cláusula WHERE filtra linhas com uma condição booleana, avaliada por linha antes de o resultado ser montado.',
        url: 'https://www.postgresql.org/docs/current/sql-select.html#SQL-WHERE',
      },
      solution: 'select nome from disciplinas where carga_horaria >= 60',
      ordered: false,
    },
    {
      id: 'media-geral',
      title: 'Média geral das notas',
      prompt: 'Calcule a média das notas de matrículas já concluídas (aprovado ou reprovado).',
      hint: "Ignore quem ainda está cursando: situacao <> 'cursando'.",
      concept: {
        text: 'AVG é uma função de agregação: reduz várias linhas de entrada a um único valor, ignorando valores NULL — as matrículas em curso, sem nota, não entram na conta.',
        url: 'https://www.postgresql.org/docs/current/functions-aggregate.html',
      },
      solution: "select avg(nota) from matriculas where situacao <> 'cursando'",
      ordered: false,
    },
    {
      id: 'alunos-por-disciplina',
      title: 'Alunos por disciplina',
      prompt: 'Para cada disciplina, mostre o nome dela e quantos alunos estão matriculados nela.',
      hint: 'Uma disciplina pode não ter matrícula nenhuma — o JOIN precisa mantê-la mesmo assim.',
      concept: {
        text: 'LEFT JOIN mantém todas as linhas da tabela à esquerda, preenchendo com NULL onde não há correspondência — diferente do JOIN comum (INNER), que descarta o que não casa.',
        url: 'https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-JOIN',
      },
      solution: `select d.nome, count(m.id)
from disciplinas d
left join matriculas m on m.disciplina_id = d.id
group by d.id, d.nome`,
      ordered: false,
    },
    {
      id: 'sem-matricula',
      title: 'Alunos sem matrícula',
      prompt: 'Liste o nome dos alunos que não estão matriculados em nenhuma disciplina.',
      hint: 'NOT EXISTS, ou um LEFT JOIN procurando a ausência do outro lado.',
      concept: {
        text: 'NOT EXISTS testa a ausência de qualquer linha que satisfaça uma subconsulta correlacionada — a forma direta de expressar "para o qual não existe".',
        url: 'https://www.postgresql.org/docs/current/functions-subquery.html#FUNCTIONS-SUBQUERY-EXISTS',
      },
      solution: `select nome from alunos a
where not exists (select 1 from matriculas m where m.aluno_id = a.id)`,
      ordered: false,
    },
    {
      id: 'media-por-disciplina',
      title: 'Média por disciplina',
      prompt:
        'Mostre cada disciplina e a média das notas já lançadas nela, da maior média para a menor.',
      hint: 'Aqui a ordem das linhas faz parte da resposta.',
      concept: {
        text: 'GROUP BY reúne as linhas por disciplina antes da agregação; ORDER BY, depois, decide a ordem final das linhas do resultado.',
        url: 'https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-GROUP',
      },
      solution: `select d.nome, avg(m.nota) as media
from matriculas m
join disciplinas d on d.id = m.disciplina_id
where m.nota is not null
group by d.id, d.nome
order by media desc`,
      ordered: true,
    },
  ],
};
