import { insert, Random } from '../random.js';
import type { Scenario } from '../scenario.js';
import { addDays, fullNames } from './names.js';

const schema = `
create table departamentos (
  id integer generated by default as identity primary key,
  nome text not null
);

create table funcionarios (
  id integer generated by default as identity primary key,
  nome text not null,
  departamento_id integer not null references departamentos (id),
  cargo text not null,
  salario numeric(10, 2) not null check (salario > 0),
  admitido_em date not null
);`;

const departamentos = ['Engenharia', 'Vendas', 'Financeiro', 'Suporte'] as const;
const cargos = ['Analista', 'Analista Sênior', 'Coordenador', 'Especialista'] as const;

function seed(variant: number): string {
  const random = new Random(7_000 + variant * 4_009_837);
  const pick = <T>(items: readonly T[]) => random.pick(items);

  const departamentoRows = departamentos.map((nome, i) => ({ id: i + 1, nome }));

  const funcionarios = fullNames(pick, 20).map((nome, i) => {
    const departamentoId = (i % departamentos.length) + 1;
    // A base per role, jittered so ties inside a department are vanishingly unlikely.
    const base = 4_500 + pick(cargos).length * 120;
    const salario = Math.round(base * (0.8 + random.next() * 1.6) * 100) / 100;
    return {
      id: i + 1,
      nome,
      departamentoId,
      cargo: pick(cargos),
      salario,
      admitidoEm: addDays('2020-01-01', random.int(0, 2_100)),
    };
  });

  return [
    insert(
      'departamentos',
      ['id', 'nome'],
      departamentoRows.map((d) => [d.id, d.nome]),
    ),
    insert(
      'funcionarios',
      ['id', 'nome', 'departamento_id', 'cargo', 'salario', 'admitido_em'],
      funcionarios.map((f) => [
        f.id,
        f.nome,
        f.departamentoId,
        f.cargo,
        f.salario.toFixed(2),
        f.admitidoEm,
      ]),
    ),
    `select setval(pg_get_serial_sequence('departamentos', 'id'), ${departamentoRows.length}),
            setval(pg_get_serial_sequence('funcionarios', 'id'), ${funcionarios.length});`,
  ].join('\n\n');
}

export const folhaPagamento: Scenario = {
  id: 'folha-pagamento',
  title: 'Folha de pagamento',
  summary: 'Departamentos e funcionários de uma empresa, com cargos, salários e admissões.',
  level: 'avançado',
  schema,
  seed,
  starter: `-- Explore os dados. Ctrl+Enter executa.
select f.nome, d.nome as departamento, f.cargo, f.salario
from funcionarios f
join departamentos d on d.id = f.departamento_id
order by f.salario desc
limit 10;`,
  challenges: [
    {
      id: 'massa-por-departamento',
      title: 'Massa salarial por departamento',
      prompt:
        'Mostre cada departamento e a soma dos salários dos funcionários nele, do maior total para o menor.',
      concept: {
        text: 'GROUP BY reúne as linhas por departamento antes da agregação; ORDER BY, depois, decide a ordem final das linhas do resultado.',
        url: 'https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-GROUP',
      },
      solution: `select d.nome, sum(f.salario) as total
from funcionarios f
join departamentos d on d.id = f.departamento_id
group by d.id, d.nome
order by total desc`,
      ordered: true,
    },
    {
      id: 'ranking-departamento',
      title: 'Ranking salarial no departamento',
      prompt:
        'Para cada funcionário, mostre o nome, o nome do departamento e a posição dele no ranking salarial dentro do próprio departamento (1 para o maior salário). Ordene por departamento e depois pela posição.',
      hint: 'RANK() OVER (PARTITION BY ... ORDER BY ...) numera as linhas dentro de cada partição, sem misturar departamentos.',
      concept: {
        text: 'Uma função de janela como RANK() calcula um valor por linha olhando um conjunto de linhas relacionadas (a partição, definida por PARTITION BY), sem colapsar essas linhas em uma só — diferente de uma agregação com GROUP BY.',
        url: 'https://www.postgresql.org/docs/current/tutorial-window.html',
      },
      solution: `select f.nome, d.nome as departamento,
  rank() over (partition by f.departamento_id order by f.salario desc) as posicao
from funcionarios f
join departamentos d on d.id = f.departamento_id
order by d.nome, posicao`,
      ordered: true,
    },
    {
      id: 'gap-para-o-proximo',
      title: 'Distância para o próximo salário do departamento',
      prompt:
        'Para cada funcionário, mostre o nome dele e a diferença entre o salário do colega imediatamente acima (no mesmo departamento, pelo salário) e o seu próprio salário. Quem já é o maior salário do departamento deve aparecer com essa diferença nula.',
      hint: 'Ordene por salário decrescente dentro do departamento e olhe para a linha anterior nessa ordem: é o que LAG faz.',
      concept: {
        text: 'LAG(expr) OVER (...) devolve o valor de expr na linha anterior, segundo a ordenação da janela; LEAD faz o mesmo para a linha seguinte. Na primeira linha da partição, LAG não tem de onde vir e devolve NULL.',
        url: 'https://www.postgresql.org/docs/current/functions-window.html',
      },
      solution: `select nome,
  lag(salario) over (partition by departamento_id order by salario desc) - salario as diferenca
from funcionarios`,
      ordered: false,
    },
    {
      id: 'acima-da-media-do-departamento',
      title: 'Acima da média do departamento',
      prompt:
        'Liste o nome dos funcionários que ganham mais do que a média salarial do próprio departamento.',
      hint: 'Uma função de janela não pode ser usada direto no WHERE — calcule a média por departamento numa subconsulta e compare depois.',
      concept: {
        text: 'Funções de janela são calculadas depois do WHERE, o que impede usá-las direto nessa cláusula; para filtrar por um valor de janela, calcule-o numa subconsulta ou CTE e filtre o resultado dela.',
        url: 'https://www.postgresql.org/docs/current/tutorial-window.html',
      },
      solution: `select nome from (
  select nome, salario,
    avg(salario) over (partition by departamento_id) as media_departamento
  from funcionarios
) f
where salario > media_departamento`,
      ordered: false,
    },
    {
      id: 'folha-acumulada',
      title: 'Folha acumulada por ordem de admissão',
      prompt:
        'Ordenando os funcionários por data de admissão (e, em caso de empate, pelo id), mostre o nome e a soma acumulada dos salários até aquele funcionário, inclusive.',
      hint: 'SUM(...) OVER (ORDER BY ...) sem PARTITION BY acumula sobre a tabela inteira, na ordem da janela.',
      concept: {
        text: 'Sem PARTITION BY, uma função de janela enxerga a tabela inteira como uma única partição; com ORDER BY, SUM() OVER acumula do início da ordenação até a linha atual — uma soma corrida.',
        url: 'https://www.postgresql.org/docs/current/functions-window.html',
      },
      solution: `select nome, sum(salario) over (order by admitido_em, id) as acumulado
from funcionarios
order by admitido_em, id`,
      ordered: true,
    },
  ],
};
