import { insert, Random } from '../random.js';
import type { Scenario } from '../scenario.js';
import { addDays, fullNames } from './names.js';

const schema = `
create table authors (
  id integer generated by default as identity primary key,
  name text not null,
  country text not null
);

create table books (
  id integer generated by default as identity primary key,
  title text not null,
  author_id integer not null references authors (id),
  published_year integer not null,
  genre text not null
);

create table members (
  id integer generated by default as identity primary key,
  name text not null,
  joined_on date not null
);

create table loans (
  id integer generated by default as identity primary key,
  book_id integer not null references books (id),
  member_id integer not null references members (id),
  loaned_on date not null,
  due_on date not null,
  returned_on date,
  check (due_on > loaned_on),
  check (returned_on is null or returned_on >= loaned_on)
);`;

const authors: readonly [name: string, country: string][] = [
  ['Machado de Assis', 'Brasil'],
  ['Clarice Lispector', 'Brasil'],
  ['Graciliano Ramos', 'Brasil'],
  ['Jorge Amado', 'Brasil'],
  ['Guimarães Rosa', 'Brasil'],
  ['Carolina Maria de Jesus', 'Brasil'],
  ['Lima Barreto', 'Brasil'],
  ['Aluísio Azevedo', 'Brasil'],
  ['Rachel de Queiroz', 'Brasil'],
  ['José de Alencar', 'Brasil'],
];

/** [title, author index, year, genre] */
const books: readonly [string, number, number, string][] = [
  ['Memórias Póstumas de Brás Cubas', 0, 1881, 'Romance'],
  ['Quincas Borba', 0, 1891, 'Romance'],
  ['Dom Casmurro', 0, 1899, 'Romance'],
  ['Perto do Coração Selvagem', 1, 1943, 'Romance'],
  ['A Hora da Estrela', 1, 1977, 'Romance'],
  ['São Bernardo', 2, 1934, 'Romance'],
  ['Vidas Secas', 2, 1938, 'Romance'],
  ['Capitães da Areia', 3, 1937, 'Romance'],
  ['Gabriela, Cravo e Canela', 3, 1958, 'Romance'],
  ['Sagarana', 4, 1946, 'Contos'],
  ['Grande Sertão: Veredas', 4, 1956, 'Romance'],
  ['Quarto de Despejo', 5, 1960, 'Diário'],
  ['Triste Fim de Policarpo Quaresma', 6, 1915, 'Romance'],
  ['O Mulato', 7, 1881, 'Romance'],
  ['O Cortiço', 7, 1890, 'Romance'],
  ['O Quinze', 8, 1930, 'Romance'],
  ['O Guarani', 9, 1857, 'Romance'],
  ['Iracema', 9, 1865, 'Romance'],
];

/** "Today" for the overdue challenge. Fixed, so answers do not depend on the clock. */
const TODAY = '2026-03-01';

function seed(variant: number): string {
  const random = new Random(2_000 + variant * 104_729);
  const pick = <T>(items: readonly T[]) => random.pick(items);

  // One author has nothing on the shelf, so counting books per author needs a LEFT JOIN.
  const absentAuthor = random.int(0, authors.length - 1);
  const shelf = books
    .map(([title, author, year, genre]) => ({ title, author, year, genre }))
    .filter((book) => book.author !== absentAuthor && random.next() < 0.85)
    .map((book, i) => ({ ...book, id: i + 1 }));

  // Distinct join dates: the "most recent members first" challenge must have one order.
  const joinOffsets = random.sample(
    Array.from({ length: 700 }, (_, i) => i),
    10,
  );
  const members = fullNames(pick, 10).map((name, i) => ({
    id: i + 1,
    name,
    joinedOn: addDays('2024-01-01', joinOffsets[i]!),
  }));

  const loans = Array.from({ length: 28 }, (_, i) => {
    const loanedOn = addDays('2026-01-05', random.int(0, 50));
    const dueOn = addDays(loanedOn, 14);
    const returned = random.next() < 0.6;
    return {
      id: i + 1,
      // Most loans go to a few books, leaving some books never borrowed.
      bookId: pick(shelf.slice(0, Math.max(1, shelf.length - 3))).id,
      memberId: pick(members).id,
      loanedOn,
      dueOn,
      returnedOn: returned ? addDays(loanedOn, random.int(1, 20)) : null,
    };
  });

  return [
    insert(
      'authors',
      ['id', 'name', 'country'],
      authors.map(([name, country], i) => [i + 1, name, country]),
    ),
    insert(
      'books',
      ['id', 'title', 'author_id', 'published_year', 'genre'],
      shelf.map((b) => [b.id, b.title, b.author + 1, b.year, b.genre]),
    ),
    insert(
      'members',
      ['id', 'name', 'joined_on'],
      members.map((m) => [m.id, m.name, m.joinedOn]),
    ),
    insert(
      'loans',
      ['id', 'book_id', 'member_id', 'loaned_on', 'due_on', 'returned_on'],
      loans.map((l) => [l.id, l.bookId, l.memberId, l.loanedOn, l.dueOn, l.returnedOn]),
    ),
    `select setval(pg_get_serial_sequence('authors', 'id'), ${authors.length}),
            setval(pg_get_serial_sequence('books', 'id'), ${Math.max(shelf.length, 1)}),
            setval(pg_get_serial_sequence('members', 'id'), ${members.length}),
            setval(pg_get_serial_sequence('loans', 'id'), ${loans.length});`,
  ].join('\n\n');
}

export const library: Scenario = {
  id: 'biblioteca',
  title: 'Biblioteca',
  summary: 'Autores, livros, membros e empréstimos de uma biblioteca de clássicos brasileiros.',
  level: 'iniciante',
  schema,
  seed,
  starter: `-- Explore os dados. Ctrl+Enter executa.
select b.title, a.name as autor, b.published_year
from books b
join authors a on a.id = b.author_id
order by b.published_year;`,
  challenges: [
    {
      id: 'antes-de-1950',
      title: 'Clássicos antigos',
      prompt: 'Liste o título e o ano de publicação dos livros publicados antes de 1950.',
      solution: 'select title, published_year from books where published_year < 1950',
      ordered: false,
    },
    {
      id: 'membros-recentes',
      title: 'Membros mais recentes',
      prompt:
        'Liste o nome e a data de adesão dos membros, do que entrou mais recentemente para o mais antigo.',
      hint: 'A ordem das linhas faz parte da resposta: ORDER BY ... DESC.',
      solution: 'select name, joined_on from members order by joined_on desc',
      ordered: true,
    },
    {
      id: 'livros-por-autor',
      title: 'Livros por autor',
      prompt:
        'Para cada autor, mostre o nome e quantos livros dele há no acervo — inclusive autores com zero livros.',
      hint: 'Um JOIN comum descarta autores sem livros. Qual JOIN mantém todas as linhas da esquerda?',
      solution: `select a.name, count(b.id)
from authors a
left join books b on b.author_id = a.id
group by a.id, a.name`,
      ordered: false,
    },
    {
      id: 'emprestimos-atrasados',
      title: 'Empréstimos atrasados',
      prompt: `Liste o título do livro e o nome do membro de cada empréstimo em atraso. Considere hoje como ${TODAY}: um empréstimo está atrasado se ainda não foi devolvido e o prazo (due_on) já passou.`,
      hint: 'Livro não devolvido: returned_on IS NULL. Cuidado: = NULL nunca é verdadeiro.',
      solution: `select b.title, m.name
from loans l
join books b on b.id = l.book_id
join members m on m.id = l.member_id
where l.returned_on is null and l.due_on < date '${TODAY}'`,
      ordered: false,
    },
    {
      id: 'leitores-assiduos',
      title: 'Leitores assíduos',
      prompt: 'Liste o nome dos membros que fizeram mais de 2 empréstimos.',
      hint: 'WHERE filtra linhas antes de agrupar; HAVING filtra os grupos.',
      solution: `select m.name
from members m
join loans l on l.member_id = m.id
group by m.id, m.name
having count(*) > 2`,
      ordered: false,
    },
    {
      id: 'nunca-emprestados',
      title: 'Na estante, intocados',
      prompt: 'Liste o título dos livros que nunca foram emprestados.',
      solution: `select title from books b
where not exists (select 1 from loans l where l.book_id = b.id)`,
      ordered: false,
    },
  ],
};
