import { insert, Random } from '../random.js';
import type { Scenario } from '../scenario.js';
import { addDays, cities, emailLocalPart, fullNames } from './names.js';

const schema = `
create table customers (
  id integer generated by default as identity primary key,
  name text not null,
  email text not null unique,
  city text not null
);

create table products (
  id integer generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(10, 2) not null check (price > 0)
);

create table orders (
  id integer generated by default as identity primary key,
  customer_id integer not null references customers (id),
  ordered_on date not null,
  status text not null check (status in ('pago', 'enviado', 'entregue', 'cancelado')),
  total numeric(10, 2) not null
);

create table order_items (
  order_id integer not null references orders (id),
  product_id integer not null references products (id),
  quantity integer not null check (quantity > 0),
  unit_price numeric(10, 2) not null,
  primary key (order_id, product_id)
);`;

const catalog: readonly [name: string, category: string, basePrice: number][] = [
  ['Notebook 14"', 'Informática', 3499],
  ['Monitor 27"', 'Informática', 1299],
  ['Teclado mecânico', 'Informática', 389],
  ['Mouse sem fio', 'Informática', 129],
  ['Headset', 'Áudio', 249],
  ['Caixa de som Bluetooth', 'Áudio', 459],
  ['Fone intra-auricular', 'Áudio', 89],
  ['Cadeira ergonômica', 'Escritório', 1590],
  ['Mesa regulável', 'Escritório', 2190],
  ['Luminária de mesa', 'Escritório', 159],
  ['Caderno pontilhado', 'Papelaria', 45],
  ['Caneta tinteiro', 'Papelaria', 119],
  ['Kit marca-texto', 'Papelaria', 32],
  ['Mochila para notebook', 'Acessórios', 279],
  ['Suporte para notebook', 'Acessórios', 149],
  ['Hub USB-C', 'Acessórios', 219],
];

const statuses = ['pago', 'enviado', 'entregue', 'entregue', 'entregue', 'cancelado'] as const;

function seed(variant: number): string {
  const random = new Random(1_000 + variant * 7_919);
  const pick = <T>(items: readonly T[]) => random.pick(items);

  const customers = fullNames(pick, 14).map((name, i) => ({
    id: i + 1,
    name,
    email: `${emailLocalPart(name)}${i + 1}@exemplo.com.br`,
    city: pick(cities),
  }));

  // Prices move from variant to variant, so no answer can be memorised.
  const products = catalog.map(([name, category, base], i) => ({
    id: i + 1,
    name,
    category,
    price: Math.round(base * (0.85 + random.next() * 0.3)) - 0.1,
  }));

  // Three customers never order: the "customers without orders" challenge needs them.
  const buyers = random.sample(customers, customers.length - 3);

  const orders = Array.from({ length: 36 }, (_, i) => ({
    id: i + 1,
    customerId: pick(buyers).id,
    orderedOn: addDays('2026-01-01', random.int(0, 180)),
    status: pick(statuses),
    items: random.sample(products, random.int(1, 4)).map((product) => ({
      productId: product.id,
      quantity: random.int(1, 3),
      unitPrice: product.price,
    })),
  }));

  breakBestSellerTie(orders);

  const orderRows = orders.map((o) => {
    const total = o.items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0);
    return [o.id, o.customerId, o.orderedOn, o.status, total.toFixed(2)] as (string | number)[];
  });

  return [
    insert(
      'customers',
      ['id', 'name', 'email', 'city'],
      customers.map((c) => [c.id, c.name, c.email, c.city]),
    ),
    insert(
      'products',
      ['id', 'name', 'category', 'price'],
      products.map((p) => [p.id, p.name, p.category, p.price.toFixed(2)]),
    ),
    insert('orders', ['id', 'customer_id', 'ordered_on', 'status', 'total'], orderRows),
    insert(
      'order_items',
      ['order_id', 'product_id', 'quantity', 'unit_price'],
      orders.flatMap((o) =>
        o.items.map((item) => [o.id, item.productId, item.quantity, item.unitPrice.toFixed(2)]),
      ),
    ),
    // Explicit ids bypass the identity sequences; move them past the data so the learner's
    // own inserts do not collide.
    `select setval(pg_get_serial_sequence('customers', 'id'), 14),
            setval(pg_get_serial_sequence('products', 'id'), ${products.length}),
            setval(pg_get_serial_sequence('orders', 'id'), ${orders.length});`,
  ].join('\n\n');
}

interface GeneratedOrder {
  items: { productId: number; quantity: number }[];
}

/** "Which product sold the most?" must have exactly one right answer. */
function breakBestSellerTie(orders: GeneratedOrder[]): void {
  const units = new Map<number, number>();
  for (const item of orders.flatMap((o) => o.items)) {
    units.set(item.productId, (units.get(item.productId) ?? 0) + item.quantity);
  }
  const ranked = [...units].sort((a, b) => b[1] - a[1] || a[0] - b[0]);
  const [first, second] = ranked;
  if (first && second && first[1] === second[1]) {
    const item = orders.flatMap((o) => o.items).find((i) => i.productId === first[0]);
    if (item) item.quantity += 1;
  }
}

export const onlineStore: Scenario = {
  id: 'loja-online',
  title: 'Loja online',
  summary: 'Clientes, produtos, pedidos e itens de pedido de um pequeno e-commerce.',
  level: 'iniciante',
  schema,
  seed,
  starter: `-- Explore os dados. Ctrl+Enter executa.
select o.id, c.name as cliente, o.ordered_on, o.status, o.total
from orders o
join customers c on c.id = o.customer_id
order by o.ordered_on
limit 10;`,
  challenges: [
    {
      id: 'clientes',
      title: 'Todos os clientes',
      prompt: 'Liste o nome e o e-mail de todos os clientes.',
      solution: 'select name, email from customers',
      ordered: false,
    },
    {
      id: 'pedidos-acima-de-500',
      title: 'Pedidos acima de R$ 500',
      prompt: 'Liste o id e o total dos pedidos com total acima de R$ 500.',
      hint: 'Filtre linhas com WHERE.',
      solution: 'select id, total from orders where total > 500',
      ordered: false,
    },
    {
      id: 'receita',
      title: 'Receita da loja',
      prompt: 'Calcule a receita total: a soma do total de todos os pedidos, exceto os cancelados.',
      hint: "SUM agrega várias linhas em uma. Pedidos cancelados têm status = 'cancelado'.",
      solution: "select sum(total) from orders where status <> 'cancelado'",
      ordered: false,
    },
    {
      id: 'mais-vendido',
      title: 'Produto mais vendido',
      prompt:
        'Qual produto vendeu mais unidades? Mostre o nome do produto e a quantidade total vendida.',
      hint: 'Junte order_items com products, agrupe por produto e ordene pela soma das quantidades.',
      solution: `select p.name, sum(i.quantity) as units
from order_items i
join products p on p.id = i.product_id
group by p.id, p.name
order by units desc
limit 1`,
      ordered: false,
    },
    {
      id: 'clientes-sem-pedidos',
      title: 'Clientes que nunca compraram',
      prompt: 'Liste o nome dos clientes que nunca fizeram um pedido.',
      hint: 'NOT EXISTS, ou um LEFT JOIN procurando a ausência do outro lado.',
      solution: `select name from customers c
where not exists (select 1 from orders o where o.customer_id = c.id)`,
      ordered: false,
    },
    {
      id: 'receita-por-categoria',
      title: 'Faturamento por categoria',
      prompt:
        'Mostre cada categoria e o faturamento dela (quantidade × preço unitário dos itens), da maior para a menor.',
      hint: 'Aqui a ordem das linhas faz parte da resposta.',
      solution: `select p.category, sum(i.quantity * i.unit_price) as revenue
from order_items i
join products p on p.id = i.product_id
group by p.category
order by revenue desc`,
      ordered: true,
    },
  ],
};
