import { insert, Random } from '../random.js';
import type { Scenario } from '../scenario.js';
import { fullNames } from './names.js';

const schema = `
create table funcionarios (
  id integer generated by default as identity primary key,
  nome text not null,
  cargo text not null,
  gerente_id integer references funcionarios (id)
);`;

function seed(variant: number): string {
  const random = new Random(8_000 + variant * 1_800_451);
  const pick = <T>(items: readonly T[]) => random.pick(items);

  // Worst case: 1 presidente + 3 diretores + 6 gerentes (2 por diretor) + 18 analistas
  // (3 por gerente) = 28. Sized for the max so no branch ever runs out of names.
  const nomes = fullNames(pick, 28);
  let cursor = 0;
  const next = () => nomes[cursor++]!;

  const funcionarios: { id: number; nome: string; cargo: string; gerenteId: number | null }[] = [];
  let id = 1;

  const presidente = { id: id++, nome: next(), cargo: 'Presidente', gerenteId: null };
  funcionarios.push(presidente);

  for (let d = 0; d < 3; d++) {
    const diretor = { id: id++, nome: next(), cargo: 'Diretor', gerenteId: presidente.id };
    funcionarios.push(diretor);

    const gerentes = random.int(1, 2);
    for (let g = 0; g < gerentes; g++) {
      const gerente = { id: id++, nome: next(), cargo: 'Gerente', gerenteId: diretor.id };
      funcionarios.push(gerente);

      const analistas = random.int(1, 3);
      for (let a = 0; a < analistas; a++) {
        funcionarios.push({ id: id++, nome: next(), cargo: 'Analista', gerenteId: gerente.id });
      }
    }
  }

  return [
    insert(
      'funcionarios',
      ['id', 'nome', 'cargo', 'gerente_id'],
      funcionarios.map((f) => [f.id, f.nome, f.cargo, f.gerenteId]),
    ),
    `select setval(pg_get_serial_sequence('funcionarios', 'id'), ${funcionarios.length});`,
  ].join('\n\n');
}

export const organograma: Scenario = {
  id: 'organograma',
  title: 'Organograma',
  summary: 'Funcionários de uma empresa organizados numa hierarquia de gerência.',
  level: 'avançado',
  schema,
  seed,
  starter: `-- Explore os dados. Ctrl+Enter executa.
select f.nome, f.cargo, g.nome as gerente
from funcionarios f
left join funcionarios g on g.id = f.gerente_id
order by f.id
limit 10;`,
  challenges: [
    {
      id: 'presidente',
      title: 'O topo da hierarquia',
      prompt: 'Liste o nome de quem não tem gerente.',
      concept: {
        text: 'NULL representa a ausência de valor; para testá-la, use IS NULL — uma comparação com = nunca é verdadeira contra NULL.',
        url: 'https://www.postgresql.org/docs/current/functions-comparison.html#FUNCTIONS-COMPARISON-NULL-COMPARISON',
      },
      solution: 'select nome from funcionarios where gerente_id is null',
      ordered: false,
    },
    {
      id: 'subordinados-diretos-presidente',
      title: 'Subordinados diretos do presidente',
      prompt: 'Liste o nome dos funcionários cujo gerente é o presidente (quem não tem gerente).',
      hint: 'Uma subconsulta escalar encontra o id de quem não tem gerente; compare gerente_id com ela.',
      concept: {
        text: 'Uma tabela pode ser referenciada mais de uma vez numa mesma consulta, sob apelidos diferentes — aqui, uma vez para o funcionário e outra, via subconsulta, para localizar o topo da hierarquia.',
        url: 'https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-JOIN',
      },
      solution: `select nome from funcionarios
where gerente_id = (select id from funcionarios where gerente_id is null)`,
      ordered: false,
    },
    {
      id: 'sem-subordinados',
      title: 'Quem não gerencia ninguém',
      prompt: 'Liste o nome dos funcionários que não aparecem como gerente de ninguém.',
      concept: {
        text: 'NOT EXISTS testa a ausência de qualquer linha que satisfaça uma subconsulta correlacionada — a forma direta de expressar "para o qual não existe".',
        url: 'https://www.postgresql.org/docs/current/functions-subquery.html#FUNCTIONS-SUBQUERY-EXISTS',
      },
      solution: `select nome from funcionarios f
where not exists (select 1 from funcionarios s where s.gerente_id = f.id)`,
      ordered: false,
    },
    {
      id: 'nivel-hierarquico',
      title: 'Nível hierárquico de cada um',
      prompt:
        'Mostre o nome de cada funcionário e o nível dele na hierarquia: 0 para quem não tem gerente, 1 para quem se reporta a ele, e assim por diante. Ordene pelo nível e, dentro do nível, pelo nome.',
      hint: 'Uma CTE recursiva começa por um caso base (nível 0) e junta a si mesma para alcançar o próximo nível.',
      concept: {
        text: 'WITH RECURSIVE define uma consulta em duas partes: um termo base e um termo recursivo que referencia a própria CTE, unidos por UNION ALL — a execução repete o termo recursivo até ele não produzir mais linhas novas.',
        url: 'https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-RECURSIVE',
      },
      solution: `with recursive niveis as (
  select id, nome, 0 as nivel from funcionarios where gerente_id is null
  union all
  select f.id, f.nome, n.nivel + 1
  from funcionarios f
  join niveis n on n.id = f.gerente_id
)
select nome, nivel from niveis
order by nivel, nome`,
      ordered: true,
    },
    {
      id: 'subordinados-por-diretor',
      title: 'Subordinados de cada diretor',
      prompt:
        'Para cada diretor, mostre o nome dele e quantos subordinados ele tem ao todo, diretos e indiretos (gerentes e analistas abaixo dele). Ordene pelo nome do diretor.',
      hint: 'Uma CTE recursiva a partir de cada diretor alcança toda a árvore abaixo dele; depois é só contar por diretor.',
      concept: {
        text: 'O termo base de uma CTE recursiva não precisa ser um único ponto de partida: partir de várias linhas ao mesmo tempo (aqui, todos os diretores) faz a recursão explorar uma subárvore para cada uma, em paralelo.',
        url: 'https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-RECURSIVE',
      },
      solution: `with recursive arvore as (
  select id as diretor_id, nome as diretor, id as subordinado_id
  from funcionarios where cargo = 'Diretor'
  union all
  select a.diretor_id, a.diretor, f.id
  from funcionarios f
  join arvore a on f.gerente_id = a.subordinado_id
)
select diretor, count(*) - 1 as subordinados
from arvore
group by diretor_id, diretor
order by diretor`,
      ordered: true,
    },
  ],
};
