import { insert, Random } from '../random.js';
import type { Scenario } from '../scenario.js';
import { addDays, fullNames } from './names.js';

const schema = `
create table assinantes (
  id integer generated by default as identity primary key,
  nome text not null,
  plano text not null check (plano in ('básico', 'padrão', 'premium')),
  criado_em date not null
);

create table titulos (
  id integer generated by default as identity primary key,
  nome text not null,
  tipo text not null check (tipo in ('filme', 'série')),
  genero text not null,
  duracao_min integer not null check (duracao_min > 0)
);

create table sessoes (
  id integer generated by default as identity primary key,
  assinante_id integer not null references assinantes (id),
  titulo_id integer not null references titulos (id),
  assistido_em timestamp not null,
  minutos_assistidos integer not null check (minutos_assistidos > 0)
);`;

const catalogo: readonly [nome: string, tipo: 'filme' | 'série', genero: string, min: number][] = [
  ['Órbita Silenciosa', 'filme', 'Ficção', 118],
  ['Noite em Belém', 'filme', 'Drama', 102],
  ['Risadas do Recife', 'filme', 'Comédia', 95],
  ['O Último Vagão', 'filme', 'Suspense', 110],
  ['Cerrado Adentro', 'série', 'Documentário', 45],
  ['Delegacia 12', 'série', 'Suspense', 48],
  ['Sabor de Família', 'série', 'Comédia', 32],
  ['Fronteira Sul', 'série', 'Drama', 50],
  ['Constelação Perdida', 'filme', 'Ficção', 131],
  ['Praia do Fim', 'série', 'Drama', 41],
];

const planos = ['básico', 'básico', 'padrão', 'padrão', 'premium'] as const;

function seed(variant: number): string {
  const random = new Random(4_000 + variant * 2_100_919);
  const pick = <T>(items: readonly T[]) => random.pick(items);

  const assinantes = fullNames(pick, 12).map((name, i) => ({
    id: i + 1,
    nome: name,
    plano: pick(planos),
    criadoEm: addDays('2025-06-01', random.int(0, 300)),
  }));

  const titulos = catalogo.map(([nome, tipo, genero, min], i) => ({
    id: i + 1,
    nome,
    tipo,
    genero,
    // Duration jitters a little per variant, so "sessões longas" is never memorised.
    duracaoMin: Math.max(10, Math.round(min * (0.92 + random.next() * 0.16))),
  }));

  // One title never gets watched, and which one moves with the variant, so the answer to
  // the "never watched" challenge cannot be memorised.
  const neverWatchedIndex = random.int(0, titulos.length - 1);
  const watched = titulos.filter((_, i) => i !== neverWatchedIndex);
  // Two subscribers never watch anything: the "total watched" challenge needs zeros.
  const viewers = random.sample(assinantes, assinantes.length - 2);

  const sessoes = Array.from({ length: 60 }, (_, i) => {
    const titulo = pick(watched);
    const dia = addDays('2026-01-01', random.int(0, 89));
    const hora = String(random.int(18, 23)).padStart(2, '0');
    return {
      id: i + 1,
      assinanteId: pick(viewers).id,
      tituloId: titulo.id,
      assistidoEm: `${dia} ${hora}:00:00`,
      // Almost always well under the runtime, sometimes right up against it.
      minutosAssistidos: Math.min(
        titulo.duracaoMin,
        Math.round(titulo.duracaoMin * (0.3 + random.next() * 0.75)),
      ),
    };
  });

  return [
    insert(
      'assinantes',
      ['id', 'nome', 'plano', 'criado_em'],
      assinantes.map((a) => [a.id, a.nome, a.plano, a.criadoEm]),
    ),
    insert(
      'titulos',
      ['id', 'nome', 'tipo', 'genero', 'duracao_min'],
      titulos.map((t) => [t.id, t.nome, t.tipo, t.genero, t.duracaoMin]),
    ),
    insert(
      'sessoes',
      ['id', 'assinante_id', 'titulo_id', 'assistido_em', 'minutos_assistidos'],
      sessoes.map((s) => [s.id, s.assinanteId, s.tituloId, s.assistidoEm, s.minutosAssistidos]),
    ),
    `select setval(pg_get_serial_sequence('assinantes', 'id'), ${assinantes.length}),
            setval(pg_get_serial_sequence('titulos', 'id'), ${titulos.length}),
            setval(pg_get_serial_sequence('sessoes', 'id'), ${sessoes.length});`,
  ].join('\n\n');
}

export const streaming: Scenario = {
  id: 'streaming',
  title: 'Streaming',
  summary: 'Assinantes, catálogo e sessões de reprodução de um serviço de streaming.',
  level: 'intermediário',
  schema,
  seed,
  starter: `-- Explore os dados. Ctrl+Enter executa.
select a.nome, t.nome as titulo, s.assistido_em, s.minutos_assistidos
from sessoes s
join assinantes a on a.id = s.assinante_id
join titulos t on t.id = s.titulo_id
order by s.assistido_em desc
limit 10;`,
  challenges: [
    {
      id: 'premium',
      title: 'Assinantes premium',
      prompt: 'Liste o nome e a data de criação dos assinantes do plano premium.',
      concept: {
        text: 'A cláusula WHERE filtra linhas com uma condição booleana, avaliada por linha antes de o resultado ser montado.',
        url: 'https://www.postgresql.org/docs/current/sql-select.html#SQL-WHERE',
      },
      solution: "select nome, criado_em from assinantes where plano = 'premium'",
      ordered: false,
    },
    {
      id: 'minutos-por-assinante',
      title: 'Minutos assistidos por assinante',
      prompt:
        'Para cada assinante, mostre o nome e o total de minutos assistidos — inclusive quem nunca assistiu nada (0 minutos).',
      hint: 'Um JOIN comum descarta quem não tem sessão. LEFT JOIN mantém, e a soma vira NULL: SUM só soma o que existe, então some COALESCE.',
      concept: {
        text: 'COALESCE devolve o primeiro argumento que não é NULL — útil depois de um LEFT JOIN, onde uma agregação sobre linhas ausentes resulta em NULL em vez de zero.',
        url: 'https://www.postgresql.org/docs/current/functions-conditional.html#FUNCTIONS-COALESCE-NVL-IFNULL',
      },
      solution: `select a.nome, coalesce(sum(s.minutos_assistidos), 0) as minutos
from assinantes a
left join sessoes s on s.assinante_id = a.id
group by a.id, a.nome`,
      ordered: false,
    },
    {
      id: 'nunca-assistidos',
      title: 'Títulos parados na prateleira',
      prompt: 'Liste o nome dos títulos que nunca foram assistidos por ninguém.',
      concept: {
        text: 'NOT EXISTS testa a ausência de qualquer linha que satisfaça uma subconsulta correlacionada — a forma direta de expressar "para o qual não existe".',
        url: 'https://www.postgresql.org/docs/current/functions-subquery.html#FUNCTIONS-SUBQUERY-EXISTS',
      },
      solution: `select nome from titulos t
where not exists (select 1 from sessoes s where s.titulo_id = t.id)`,
      ordered: false,
    },
    {
      id: 'sessoes-completas',
      title: 'Quem assistiu até (quase) o fim',
      prompt:
        'Liste o nome do assinante e o nome do título das sessões em que ele assistiu a pelo menos 90% da duração do título.',
      hint: 'Compare duas colunas de tabelas diferentes na mesma condição: minutos_assistidos contra duracao_min.',
      concept: {
        text: 'Uma condição de junção ou de filtro pode comparar colunas de tabelas diferentes livremente — o WHERE não se limita a comparar uma coluna com uma constante.',
        url: 'https://www.postgresql.org/docs/current/sql-select.html#SQL-WHERE',
      },
      solution: `select a.nome, t.nome as titulo
from sessoes s
join assinantes a on a.id = s.assinante_id
join titulos t on t.id = s.titulo_id
where s.minutos_assistidos >= 0.9 * t.duracao_min`,
      ordered: false,
    },
    {
      id: 'acima-da-media',
      title: 'Acima da média',
      prompt:
        'Entre os assinantes que assistiram a algo, liste o nome dos que somaram mais minutos assistidos do que a média desse total entre eles.',
      hint: 'Primeiro monte, numa subconsulta, o total por assinante; depois compare cada total com a média de todos eles.',
      concept: {
        text: 'Uma subconsulta na cláusula FROM funciona como uma tabela: pode ser agregada, filtrada e comparada como qualquer outra, o que permite comparar cada grupo com uma métrica calculada sobre todos os grupos.',
        url: 'https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-SUBQUERIES',
      },
      solution: `select nome, total from (
  select a.id, a.nome, sum(s.minutos_assistidos) as total
  from assinantes a
  join sessoes s on s.assinante_id = a.id
  group by a.id, a.nome
) por_assinante
where total > (select avg(total) from (
  select assinante_id, sum(minutos_assistidos) as total
  from sessoes
  group by assinante_id
) t)`,
      ordered: false,
    },
    {
      id: 'minutos-por-genero',
      title: 'Minutos por gênero',
      prompt:
        'Mostre cada gênero e o total de minutos assistidos em títulos desse gênero, do maior para o menor.',
      hint: 'Junte sessões com títulos para saber o gênero de cada sessão, agrupe por gênero e ordene pela soma.',
      concept: {
        text: 'GROUP BY reúne as linhas por gênero antes da agregação; ORDER BY, depois, decide a ordem final das linhas do resultado.',
        url: 'https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-GROUP',
      },
      solution: `select t.genero, sum(s.minutos_assistidos) as minutos
from sessoes s
join titulos t on t.id = s.titulo_id
group by t.genero
order by minutos desc`,
      ordered: true,
    },
  ],
};
