import type { Lab } from '../lab.js';

const setup = `
create table usuarios (
  id integer generated by default as identity primary key,
  email text not null unique,
  nome text not null,
  ativo boolean not null default true
);

insert into usuarios (email, nome, ativo) values
  ('ana@exemplo.com', 'Ana Ribeiro', true),
  ('bruno@exemplo.com', 'Bruno Alves', true),
  ('carla@exemplo.com', 'Carla Souza', false);`;

/**
 * Before the deep dive de "SQL Injection, vista pela árvore", os dois blocos mais simples
 * de montar à mão: um OR sempre verdadeiro, e um comentário que apaga o resto da consulta.
 * A aplicação aqui tem uma segunda defesa — "and ativo = true" — que o comentário derruba.
 */
export const comentariosSql: Lab = {
  id: 'comentarios-sql',
  title: 'Comentários SQL e o OR sempre verdadeiro',
  summary:
    'Antes da árvore inteira: veja um OR que nunca é falso, e um comentário -- apagando um filtro que a aplicação escreveu para proteger contas banidas.',
  level: 'iniciante',
  panel: 'ast',
  premise:
    'Uma aplicação monta assim: "... where email = \'" + digitado + "\' and ativo = true" — pensada para nunca devolver uma conta banida. Você vai digitar no lugar do usuário e ver o que sobra da consulta depois que o banco a lê.',
  steps: [
    {
      id: 'normal',
      title: 'O que a aplicação esperava',
      brief:
        'Um e-mail comum, de uma conta ativa. A árvore tem duas comparações unidas por AND: o texto digitado é só um valor.',
      sql: "select id, nome, email from usuarios where email = 'ana@exemplo.com' and ativo = true;",
      expect:
        'Uma linha. Guarde esta árvore: é o formato "correto" com que as outras serão comparadas.',
      rows: 1,
      concept: {
        text: 'Uma constante de texto entre aspas simples é um valor literal; comparada com = numa cláusula WHERE, ela nunca altera a estrutura da consulta, só o que é filtrado.',
        url: 'https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS',
      },
    },
    {
      id: 'tautologia',
      title: "Digitando ' or '1'='1",
      brief:
        'O texto fechou a aspa e continuou escrevendo a consulta. A árvore ganhou um nó que a aplicação nunca escreveu: um OR.',
      sql: "select id, nome, email from usuarios where email = '' or '1'='1' and ativo = true;",
      expect:
        'As duas contas ativas — mas não a banida: AND ainda une "\'1\'=\'1\'" a "ativo = true", então esse ramo do OR continua exigindo ativo = true.',
      rows: 2,
      concept: {
        text: 'AND tem precedência maior que OR: "a or b and c" é lido como "a or (b and c)", não como "(a or b) and c". Uma tautologia dentro de um AND não liberta a condição do resto dele.',
        url: 'https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-PRECEDENCE',
      },
    },
    {
      id: 'comentario',
      title: 'Apagando o resto com --',
      brief:
        'A mesma tautologia, agora seguida de --. Tudo depois vira comentário para o banco — inclusive o "and ativo = true" que a aplicação escreveu.',
      sql: "select id, nome, email from usuarios where email = '' or '1'='1' -- and ativo = true;",
      expect:
        'As três contas, banida inclusive. O -- não aparece na árvore — comentário é removido antes de qualquer análise — mas o efeito dele é ter apagado a condição que ficava depois.',
      rows: 3,
      concept: {
        text: '-- inicia um comentário que vai até o fim da linha; /* ... */ comenta um trecho em qualquer lugar, inclusive no meio de uma linha. Comentários são descartados antes de a consulta ser interpretada, então nunca aparecem na árvore.',
        url: 'https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-COMMENTS',
      },
    },
  ],
  setup,
};
