import type { Lab } from '../lab.js';

const setup = `
create table usuarios (
  id integer generated by default as identity primary key,
  email text not null unique,
  nome text not null,
  admin boolean not null default false
);

create table cartoes (
  id integer generated by default as identity primary key,
  usuario_id integer not null references usuarios (id),
  numero text not null,
  validade text not null
);

insert into usuarios (email, nome, admin) values
  ('ana@exemplo.com', 'Ana Ribeiro', false),
  ('bruno@exemplo.com', 'Bruno Alves', false),
  ('root@exemplo.com', 'Administração', true);

insert into cartoes (usuario_id, numero, validade) values
  (1, '4111 1111 1111 1111', '12/29'),
  (2, '5500 0000 0000 0004', '03/28'),
  (3, '3400 0000 0000 009', '07/30');`;

/**
 * The lab's thesis: injection is not about quotes, it is about who decides the *shape* of
 * the query. Every step runs the same kind of query and watches the parse tree, which is
 * what PostgreSQL actually executes.
 */
export const sqlInjection: Lab = {
  id: 'sql-injection',
  title: 'SQL Injection, vista pela árvore',
  summary:
    'Concatenar texto deixa o usuário escrever a consulta junto com você. Compare a árvore sintática do que a aplicação queria com a do que o banco recebeu.',
  level: 'intermediário',
  panel: 'ast',
  premise:
    'Uma aplicação monta a consulta juntando texto: "select * from usuarios where email = \'" + digitado + "\'". Você vai digitar no lugar do usuário e ver o que acontece com a árvore da consulta — a estrutura que o PostgreSQL executa, que é onde o ataque aparece.',
  steps: [
    {
      id: 'normal',
      title: 'O que a aplicação esperava',
      brief:
        'Um e-mail comum no campo de busca. A árvore tem um filtro comparando a coluna email com uma constante: o texto digitado é um valor, e só.',
      sql: "select id, nome, email from usuarios where email = 'ana@exemplo.com';",
      expect:
        'Uma linha. Guarde esta árvore: ela é o formato "correto" com que as outras serão comparadas.',
      rows: 1,
      concept: {
        text: 'Uma constante de texto entre aspas simples é um valor literal; comparada com = numa cláusula WHERE, ela nunca altera a estrutura da consulta, só o que é filtrado.',
        url: 'https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS',
      },
    },
    {
      id: 'tautologia',
      title: "Digitando ' or '1'='1",
      brief:
        'O mesmo campo, outro conteúdo. Nada foi "quebrado": o texto fechou a aspa e continuou escrevendo a consulta.',
      sql: "select id, nome, email from usuarios where email = '' or '1'='1';",
      expect:
        'Todas as linhas. Na árvore, o filtro deixou de ser uma comparação e virou um OR — um nó que a aplicação nunca escreveu.',
      rows: 3,
      concept: {
        text: 'OR combina duas condições booleanas: o resultado é verdadeiro se qualquer uma delas for verdadeira. Uma condição sempre verdadeira, como \'1\'=\'1\', faz o OR inteiro ser sempre verdadeiro — é o que se chama de tautologia.',
        url: 'https://www.postgresql.org/docs/current/functions-logical.html',
      },
    },
    {
      id: 'union',
      title: 'Lendo outra tabela',
      brief:
        'Uma tautologia mostra linhas demais da mesma tabela. Um UNION muda de tabela — e a árvore deixa de ter uma consulta para ter duas.',
      sql: `select id, nome, email from usuarios where email = ''
union all
select id, numero, validade from cartoes;`,
      expect:
        'Números de cartão numa tela de busca de usuários. O nó raiz agora é um SelectStmt com op = SETOP_UNION: outra forma, não outro valor.',
      rows: 3,
      concept: {
        text: 'UNION (e UNION ALL) combina os resultados de duas consultas SELECT em um só, desde que tenham o mesmo número de colunas e tipos compatíveis. UNION ALL mantém duplicatas; UNION as remove.',
        url: 'https://www.postgresql.org/docs/current/queries-union.html',
      },
    },
    {
      id: 'parametro',
      title: 'Com parâmetro, o formato é seu',
      brief:
        'A mesma busca, com o valor fora do texto da consulta. O banco recebe a consulta e o valor por caminhos separados. O prepare fica guardado na sessão, por isso o passo começa descartando o de uma execução anterior.',
      sql: "deallocate all;\nprepare busca (text) as select id, nome, email from usuarios where email = $1;\nexecute busca (''' or ''1''=''1');",
      expect:
        'Zero linhas — e nenhum erro. O parâmetro virou um ParamRef na árvore: o que o usuário digita vai para dentro do nó, nunca vira um nó.',
      rows: 0,
      concept: {
        text: 'PREPARE cria uma consulta com parâmetros ($1, $2, ...) cuja estrutura é fixada antes de qualquer valor chegar; EXECUTE só preenche os parâmetros, nunca reinterpreta texto como SQL.',
        url: 'https://www.postgresql.org/docs/current/sql-prepare.html',
      },
    },
    {
      id: 'escape-nao-basta',
      title: 'Por que escapar aspas não resolve',
      brief:
        'Em contexto numérico não há aspa nenhuma para escapar. Uma função que "limpa aspas" não protege este caso.',
      sql: 'select id, nome, email from usuarios where id = 1 or 1 = 1;',
      expect:
        'Todas as linhas de novo, sem uma única aspa envolvida. A defesa é o parâmetro, não a limpeza do texto.',
      rows: 3,
      concept: {
        text: 'Os operadores de comparação (=, <>, <, >, ...) funcionam sobre qualquer tipo, não só texto entre aspas — inclusive números, onde não há aspa para "escapar".',
        url: 'https://www.postgresql.org/docs/current/functions-comparison.html',
      },
    },
  ],
  setup,
};
