import type { Lab } from '../lab.js';

/**
 * The seed runs as superuser while the sandbox container starts (ADR 0002). It builds the
 * tables the mini-app searches and then grants the `lab` role — the one the app connects
 * as — only what a search of `usuarios` needs. `cartoes` is never granted, so reaching it
 * is a privilege error, not a leak: least privilege is the defence (ADR 0001), and the lab
 * makes the learner feel it.
 */
const seed = `
create table usuarios (
  id integer generated by default as identity primary key,
  email text not null unique,
  nome text not null,
  admin boolean not null default false
);

create table cartoes (
  id integer generated by default as identity primary key,
  usuario_id integer not null references usuarios (id),
  numero text not null,
  validade text not null
);

insert into usuarios (email, nome, admin) values
  ('ana@exemplo.com', 'Ana Ribeiro', false),
  ('bruno@exemplo.com', 'Bruno Alves', false),
  ('root@exemplo.com', 'Administração', true);

insert into cartoes (usuario_id, numero, validade) values
  (1, '4111 1111 1111 1111', '12/29'),
  (2, '5500 0000 0000 0004', '03/28'),
  (3, '3400 0000 0000 009', '07/30');

-- The search app reads users, and nothing else. cartoes stays out of its reach.
grant select on usuarios to lab;`;

/**
 * The injection lab, this time against a real mini-app on a T2 sandbox (ADR 0010). The T0
 * version (sql-injection) has the learner write the whole query and watch the tree; here
 * they only type into a search field, and the app builds the SQL — first by gluing text,
 * then with a parameter. Same lesson as the tree, now with the application in the middle,
 * the way the concept (§16) frames it, plus the privilege wall the browser cannot show.
 */
export const sqlInjectionApp: Lab = {
  id: 'sql-injection-app',
  title: 'SQL Injection num app de verdade',
  summary:
    'Um app de busca monta a consulta juntando texto. Digite no lugar do usuário, veja a injeção mudar o formato da consulta, o privilégio barrar o roubo, e o parâmetro encerrar o assunto.',
  level: 'intermediário',
  panel: 'app',
  runtime: 'sandbox',
  premise:
    'Este lab roda num PostgreSQL de verdade, só seu, num container descartável no servidor. Uma aplicação de busca monta a consulta assim: "select … from usuarios where email = \'" + digitado + "\'". Você digita no campo, e vê o que o banco recebe — e por que a defesa não é limpar aspas, é o parâmetro e o privilégio mínimo.',
  steps: [
    {
      id: 'normal',
      title: 'Uma busca comum',
      brief:
        'Um e-mail no campo de busca. O app junta seu texto à consulta e o banco devolve a linha esperada: o texto foi um valor, e só.',
      input: 'ana@exemplo.com',
      mode: 'concatenated',
      expect: 'Uma linha, a da Ana. Guarde o formato desta consulta: é o "correto".',
      rows: 1,
      concept: {
        text: 'Quando o texto digitado vira apenas o valor de uma comparação (=) dentro do WHERE, ele nunca muda a estrutura da consulta — só o que é filtrado.',
        url: 'https://www.postgresql.org/docs/current/sql-select.html#SQL-WHERE',
      },
    },
    {
      id: 'tautologia',
      title: "Digitando ' or '1'='1",
      brief:
        'O mesmo campo, outro conteúdo. Nada foi "quebrado": o texto fechou a aspa e continuou escrevendo a consulta. O filtro por e-mail virou um OR que é sempre verdadeiro.',
      input: "' or '1'='1",
      mode: 'concatenated',
      expect:
        'Todos os usuários, inclusive o e-mail do admin — de uma busca que devia achar um só. O app leu a tabela toda porque a injeção ampliou o WHERE.',
      rows: 3,
      concept: {
        text: 'OR combina duas condições booleanas: o resultado é verdadeiro se qualquer uma delas for verdadeira. Uma condição sempre verdadeira, como \'1\'=\'1\', faz o OR inteiro ser sempre verdadeiro.',
        url: 'https://www.postgresql.org/docs/current/functions-logical.html',
      },
    },
    {
      id: 'union-barrado',
      title: 'Tentando puxar os cartões',
      brief:
        'Ver a tabela de usuários já é ruim; um UNION tenta pular para os cartões. A injeção monta a consulta, mas o role do app nunca recebeu permissão de ler cartoes.',
      input: "' union all select id, numero, validade from cartoes --",
      mode: 'concatenated',
      expect:
        'permission denied for table cartoes. A injeção mudou o formato da consulta, mas o privilégio mínimo transformou o roubo num erro. A defesa mora no banco, não no texto.',
      refused: '42501',
      concept: {
        text: 'UNION combina os resultados de duas consultas SELECT com o mesmo número de colunas — mas continua exigindo privilégio SELECT em cada tabela referenciada, checado no momento da execução.',
        url: 'https://www.postgresql.org/docs/current/queries-union.html',
      },
    },
    {
      id: 'parametro',
      title: 'Com parâmetro, o formato é seu',
      brief:
        'A mesma tentativa de UNION, agora com o app mandando o valor por fora do texto da consulta ($1). O banco recebe a consulta e o valor por caminhos separados.',
      input: "' union all select id, numero, validade from cartoes --",
      mode: 'parameterized',
      expect:
        'Zero linhas, e nenhum erro. Todo o texto virou o valor de um e-mail que não existe: sem aspa para fechar, sem UNION, sem nó novo. O parâmetro encerrou o assunto.',
      rows: 0,
      concept: {
        text: 'Uma consulta parametrizada (com $1 e um valor enviado separadamente) fixa a estrutura SQL antes de qualquer valor chegar: o driver nunca interpreta o conteúdo do parâmetro como texto de consulta.',
        url: 'https://www.postgresql.org/docs/current/sql-prepare.html',
      },
    },
  ],
  setup: seed,
};
