import type { Lab } from '../lab.js';

const setup = `
create table produtos (
  id integer generated by default as identity primary key,
  nome text not null,
  preco numeric(10, 2) not null check (preco > 0)
);

insert into produtos (nome, preco) values
  ('Caderno', 12.90),
  ('Caneta', 3.50),
  ('Mochila', 149.90);`;

/**
 * The prerequisite to "Roles e permissões, na prática": one role, one table, one verb at a
 * time. No inheritance, no sequences, no PUBLIC — just the fact that a role starts with
 * nothing and every capability is a GRANT away, checked one verb at a time.
 */
export const privilegiosBasicos: Lab = {
  id: 'privilegios-basicos',
  title: 'Privilégios, do zero',
  summary:
    'Uma role nasce sem acesso a nada. Veja, passo a passo, o que muda (e o que não muda) a cada GRANT.',
  level: 'iniciante',
  panel: 'privileges',
  premise:
    'Você é o dono deste banco. Vamos criar uma única role e ver, na matriz ao lado, exatamente quando ela passa a poder ler e quando passa a poder escrever — nunca antes do GRANT correspondente.',
  steps: [
    {
      id: 'criar',
      title: 'Uma role sem privilégio nenhum',
      brief:
        'Toda role nasce assim: sem acesso a nada que não seja seu. O DROP antes deixa o passo seguro para rodar de novo.',
      sql: `drop role if exists app;
create role app nologin;`,
      expect: 'A role aparece na matriz sem nenhuma marca ao lado de produtos.',
      concept: {
        text: 'CREATE ROLE cria uma role de banco. Por padrão ela não tem nenhum privilégio sobre objetos que não criou — nem mesmo ler uma tabela.',
        url: 'https://www.postgresql.org/docs/current/sql-createrole.html',
      },
    },
    {
      id: 'negado',
      title: 'Tentando ler sem permissão',
      brief:
        'SET ROLE troca quem você é dentro da sessão. É a forma honesta de testar uma permissão: pelo lado de quem a usa.',
      sql: `set role app;
select * from produtos;`,
      expect: 'permission denied for table produtos — a mensagem exata que sua aplicação veria.',
      refused: '42501',
      concept: {
        text: 'SET ROLE muda a identidade de privilégios da sessão atual para outra role, sem precisar reconectar.',
        url: 'https://www.postgresql.org/docs/current/sql-set-role.html',
      },
    },
    {
      id: 'conceder-select',
      title: 'Concedendo a leitura',
      brief: 'De volta a dono, concedemos só SELECT — nada de ALL PRIVILEGES.',
      sql: `reset role;
grant select on produtos to app;`,
      expect: 'A matriz ganha um SELECT marcado para app em produtos.',
      concept: {
        text: 'GRANT concede um privilégio específico (SELECT, INSERT, UPDATE, ...) sobre um objeto a uma role. Conceder só o verbo necessário é o princípio do menor privilégio.',
        url: 'https://www.postgresql.org/docs/current/sql-grant.html',
      },
    },
    {
      id: 'ler-mas-nao-escrever',
      title: 'Ler pode; atualizar, ainda não',
      brief: 'A mesma role, agora tentando os dois verbos.',
      sql: `set role app;
select count(*) from produtos;
update produtos set preco = preco * 1.1;`,
      expect: 'O SELECT responde 3; o UPDATE é recusado. Cada verbo precisa do seu próprio GRANT.',
      refused: '42501',
      concept: {
        text: 'Os privilégios em tabelas são concedidos por operação (SELECT, INSERT, UPDATE, DELETE, ...): ter um não implica ter os outros.',
        url: 'https://www.postgresql.org/docs/current/ddl-priv.html',
      },
    },
    {
      id: 'revogar',
      title: 'Revogando o que foi dado',
      brief: 'Fechar o que foi aberto, e conferir do lado de quem usava.',
      sql: `reset role;
revoke select on produtos from app;
set role app;
select * from produtos;`,
      expect: 'permission denied de novo — REVOKE apaga exatamente o que o GRANT tinha dado.',
      refused: '42501',
      concept: {
        text: 'REVOKE remove um privilégio concedido anteriormente, devolvendo a role ao estado de antes do GRANT.',
        url: 'https://www.postgresql.org/docs/current/sql-revoke.html',
      },
    },
  ],
  setup,
};
