import type { Lab } from '../lab.js';

const setup = `
create table clientes (
  id integer generated by default as identity primary key,
  nome text not null,
  email text not null
);

create table faturas (
  id integer generated by default as identity primary key,
  cliente_id integer not null references clientes (id),
  valor numeric(10, 2) not null check (valor >= 0),
  paga boolean not null default false
);

insert into clientes (nome, email) values
  ('Ana Ribeiro', 'ana@exemplo.com'),
  ('Bruno Alves', 'bruno@exemplo.com');

insert into faturas (cliente_id, valor, paga) values
  (1, 1200.00, true),
  (1, 340.50, false),
  (2, 89.90, false);`;

/**
 * Privileges are easier to reason about when they are visible. Each step changes one
 * grant and the matrix redraws, and `set role` lets the learner feel the change from the
 * other side instead of trusting the documentation.
 */
export const rolesAndPermissions: Lab = {
  id: 'roles-e-permissoes',
  title: 'Roles e permissões, na prática',
  summary:
    'Crie roles, conceda o mínimo, e execute como cada uma delas. A matriz ao lado mostra quem pode o quê a cada passo.',
  level: 'intermediário',
  panel: 'privileges',
  premise:
    'Você é o dono deste banco. Vamos criar duas roles de aplicação — uma que só lê, outra que também escreve — e conceder o mínimo para cada uma. Depois de cada comando, olhe a matriz: ela é lida do catálogo, não do que prometemos aqui.',
  steps: [
    {
      id: 'criar',
      title: 'Duas roles, nenhum privilégio',
      brief:
        'Uma role nasce sem acesso a nada que não seja seu. NOLOGIN porque estas existem para agrupar permissões, não para conectar.',
      sql: `create role app_leitura nologin;
create role app_escrita nologin;`,
      expect:
        'As roles aparecem na matriz sem nenhuma marca. Criar uma role não dá acesso a nada — o acesso vem dos GRANTs.',
    },
    {
      id: 'negado',
      title: 'Executando como a role',
      brief:
        'SET ROLE troca quem você é dentro da sessão, sem reconectar. É a forma honesta de testar uma permissão: pelo lado de quem a usa.',
      sql: `set role app_leitura;
select * from clientes;`,
      expect:
        'permission denied for table clientes. Guarde a mensagem: é exatamente o que sua aplicação verá se faltar um grant.',
      refused: '42501',
    },
    {
      id: 'conceder',
      title: 'O mínimo para ler',
      brief:
        'Voltamos a ser o dono para conceder. SELECT em duas tabelas — nada de ALL PRIVILEGES, que inclui apagar.',
      sql: `reset role;
grant select on clientes, faturas to app_leitura;`,
      expect: 'A matriz ganha SELECT nas duas tabelas para app_leitura.',
    },
    {
      id: 'ler',
      title: 'Ler pode; escrever, não',
      brief: 'A mesma sessão, de novo como a role de leitura, agora tentando os dois verbos.',
      sql: `set role app_leitura;
select count(*) from faturas;
update faturas set paga = true where id = 3;`,
      expect:
        'O SELECT responde 3; o UPDATE é recusado. Um privilégio por verbo, por tabela — é assim que o PostgreSQL pensa.',
      refused: '42501',
    },
    {
      id: 'herdar',
      title: 'Herança entre roles',
      brief:
        'Em vez de repetir os grants, a role de escrita herda os de leitura e ganha só o que falta.',
      sql: `reset role;
grant app_leitura to app_escrita;
grant insert, update on faturas to app_escrita;`,
      expect:
        'app_escrita passa a ser membro de app_leitura na matriz. Herdar é a forma de não duplicar — e de não esquecer de revogar em dois lugares.',
    },
    {
      id: 'escrever',
      title: 'Escrevendo com o necessário',
      brief:
        'A sequência também precisa ser concedida: INSERT numa coluna de identidade usa a sequência por trás dela.',
      sql: `set role app_escrita;
update faturas set paga = true where id = 3;
select id, paga from faturas order by id;`,
      expect: 'O UPDATE passa. A herança trouxe o SELECT; o grant novo trouxe a escrita.',
      rows: 3,
    },
    {
      id: 'public',
      title: 'PUBLIC concede a todo mundo',
      brief:
        'PUBLIC não é "todos os que você criou": é qualquer role, inclusive as que ainda não existem. É o grant que mais vaza.',
      sql: `reset role;
grant select on clientes to public;`,
      expect:
        'Na matriz, uma linha PUBLIC. Qualquer role futura já nasce podendo ler clientes — sem ninguém ter concedido nada a ela.',
    },
    {
      id: 'revogar',
      title: 'Revogando o excesso',
      brief: 'Fechar o que foi aberto, e conferir do lado de quem usava.',
      sql: `revoke select on clientes from public;
revoke insert, update on faturas from app_escrita;`,
      expect:
        'A linha PUBLIC some e app_escrita fica só com o que herdou. Revogar de PUBLIC não tira o que foi concedido diretamente a uma role: são grants diferentes.',
    },
  ],
  setup,
};
