import type { Lab } from '../lab.js';

const setup = `
create table tarefas (
  id integer generated by default as identity primary key,
  titulo text not null,
  concluida boolean not null default false
);

insert into tarefas (titulo) values
  ('Revisar contrato'),
  ('Enviar relatório'),
  ('Agendar reunião');`;

/**
 * ALL PRIVILEGES não é dono. GRANT concede verbos sobre a tabela; DROP, ALTER e RENAME
 * pedem ser dono dela (ou superusuário) — uma distinção que a matriz de privilégios, sozinha,
 * não deixa óbvia.
 */
export const propriedadeDeTabelas: Lab = {
  id: 'propriedade-de-tabelas',
  title: 'ALL PRIVILEGES não é ser dono',
  summary:
    'Conceda todos os verbos a uma role e veja mesmo assim ela não poder apagar nem alterar a tabela: isso pede ser dono.',
  level: 'iniciante',
  panel: 'privileges',
  premise:
    'Você é o dono da tabela tarefas. Vamos dar a uma role todos os privilégios de dados que existem — SELECT, INSERT, UPDATE, DELETE — e ver que ainda assim ela não manda na estrutura da tabela.',
  steps: [
    {
      id: 'conceder-tudo',
      title: 'Todos os privilégios de dados',
      brief: 'ALL PRIVILEGES aqui significa os quatro verbos de sempre — nada além disso.',
      sql: `do $$
begin
  if exists (select 1 from pg_roles where rolname = 'editor') then
    revoke all privileges on tarefas from editor;
  end if;
end $$;
drop role if exists editor;
create role editor nologin;
grant all privileges on tarefas to editor;`,
      expect: 'A matriz mostra os quatro verbos marcados para editor em tarefas.',
      concept: {
        text: 'ALL PRIVILEGES, numa tabela, expande para os privilégios de dados aplicáveis a ela (SELECT, INSERT, UPDATE, DELETE, ...) — não inclui apagar ou alterar a tabela, que pertencem ao dono.',
        url: 'https://www.postgresql.org/docs/current/sql-grant.html',
      },
    },
    {
      id: 'negar-drop',
      title: 'Tentando apagar a tabela',
      brief: 'Com todos os verbos de dados, a tentativa mais óbvia: apagar a tabela inteira.',
      sql: `set role editor;
drop table tarefas;`,
      expect: 'must be owner of table tarefas — nenhum dos quatro GRANTs cobre isso.',
      refused: '42501',
      concept: {
        text: 'DROP TABLE exige ser o dono do objeto (ou superusuário) — não existe um privilégio "DROP" que se conceda a outra role.',
        url: 'https://www.postgresql.org/docs/current/sql-droptable.html',
      },
    },
    {
      id: 'negar-alter',
      title: 'Tentando alterar a estrutura',
      brief: 'O mesmo vale para mudar a tabela, não os dados dentro dela.',
      sql: `set role editor;
alter table tarefas rename to lista_tarefas;`,
      expect:
        'must be owner of table tarefas de novo — renomear é alterar a estrutura, não os dados.',
      refused: '42501',
      concept: {
        text: 'ALTER TABLE, para qualquer mudança na definição da tabela (colunas, nome, restrições), também exige ser o dono — os privilégios de SELECT/INSERT/UPDATE/DELETE não alcançam a estrutura.',
        url: 'https://www.postgresql.org/docs/current/sql-altertable.html',
      },
    },
    {
      id: 'transferir',
      title: 'Transferindo a posse',
      brief: 'Voltamos a ser o dono para transferir a posse — a única forma de mudar isso.',
      sql: `reset role;
alter table tarefas owner to editor;`,
      expect: 'Nenhuma mudança na matriz: posse não é um privilégio concedido, não aparece nela.',
      concept: {
        text: 'ALTER TABLE ... OWNER TO transfere a posse do objeto para outra role. A posse não é um GRANT e não some com um REVOKE — só muda com outro ALTER ... OWNER TO.',
        url: 'https://www.postgresql.org/docs/current/sql-altertable.html',
      },
    },
    {
      id: 'agora-pode',
      title: 'Agora sim',
      brief:
        'Como dono, editor pode alterar a estrutura — algo que nenhum GRANT anterior permitia.',
      sql: `set role editor;
alter table tarefas add column if not exists validada boolean not null default false;
select id, titulo from tarefas order by id;`,
      expect: 'O ALTER TABLE passa, e as três tarefas continuam lá: a posse mudou, os dados não.',
      rows: 3,
      concept: {
        text: 'Como dono da tabela, uma role pode alterar sua estrutura livremente, mesmo sem nenhum GRANT explícito — a posse já inclui essa capacidade.',
        url: 'https://www.postgresql.org/docs/current/ddl-priv.html',
      },
    },
  ],
  setup,
};
