import type { Lab } from '../lab.js';

const setup = `
create table relatorios (
  id integer generated by default as identity primary key,
  departamento text not null,
  confidencial boolean not null default false,
  titulo text not null
);

insert into relatorios (departamento, confidencial, titulo) values
  ('vendas', false, 'Resumo do trimestre'),
  ('vendas', true, 'Renegociação com fornecedor'),
  ('rh', false, 'Calendário de férias'),
  ('rh', true, 'Processo disciplinar');

create role app_funcionario nologin;
grant select on relatorios to app_funcionario;`;

/**
 * O lab de RLS multi-tenant mostra uma política PERMISSIVE, o padrão: várias políticas se
 * somam com OR. Aqui a segunda regra precisa se impor sobre a primeira — e é para isso que
 * existe RESTRICTIVE, que se combina com AND em vez de OR.
 */
export const rlsRestritiva: Lab = {
  id: 'rls-permissiva-e-restritiva',
  title: 'Políticas permissivas e restritivas',
  summary:
    'Uma política PERMISSIVE amplia o que é visível; uma RESTRICTIVE só reduz. Veja por que "mais uma política" nem sempre significa "mais acesso".',
  level: 'avançado',
  panel: 'policies',
  premise:
    'A tabela relatorios tem uma coluna departamento e uma confidencial. Vamos dar a app_funcionario acesso por departamento — e depois uma segunda regra que fecha os confidenciais para todo mundo, mesmo dentro do próprio departamento.',
  steps: [
    {
      id: 'permissiva-por-departamento',
      title: 'Uma política por departamento',
      brief:
        'PERMISSIVE é o padrão de CREATE POLICY: se várias existem para o mesmo comando, uma linha passa se qualquer uma delas permitir.',
      sql: `reset role;
alter table relatorios enable row level security;
drop policy if exists por_departamento on relatorios;
create policy por_departamento on relatorios
  for select to app_funcionario
  using (departamento = current_setting('app.departamento', true));
set role app_funcionario;
set app.departamento = 'vendas';
select id, titulo from relatorios order by id;`,
      expect:
        'As duas linhas de vendas, a confidencial inclusive: a única política existente não distingue por confidencial.',
      rows: 2,
      concept: {
        text: 'Por padrão, CREATE POLICY cria uma política PERMISSIVE. Quando várias políticas permissivas se aplicam ao mesmo comando, uma linha é visível se pelo menos uma delas permitir — elas se combinam com OR.',
        url: 'https://www.postgresql.org/docs/current/sql-createpolicy.html',
      },
    },
    {
      id: 'segunda-permissiva-nao-fecha',
      title: 'Uma segunda PERMISSIVE não fecha nada',
      brief:
        'Tentativa ingênua: uma política dizendo "não confidencial". Como as duas são PERMISSIVE, elas se somam por OR — e a primeira já libera tudo do departamento.',
      sql: `reset role;
drop policy if exists nao_confidencial on relatorios;
create policy nao_confidencial on relatorios
  for select to app_funcionario
  using (confidencial = false);
set role app_funcionario;
select id, titulo from relatorios order by id;`,
      expect:
        'Três linhas: as duas de vendas (pela primeira política) mais a não confidencial do RH (pela segunda) — só falta a confidencial do RH, que nenhuma das duas libera. PERMISSIVE nunca subtrai o que outra já permitiu.',
      rows: 3,
      concept: {
        text: 'Duas políticas PERMISSIVE para o mesmo comando não se restringem uma à outra: o resultado é a união do que cada uma libera, nunca a interseção.',
        url: 'https://www.postgresql.org/docs/current/sql-createpolicy.html',
      },
    },
    {
      id: 'restritiva',
      title: 'RESTRICTIVE de verdade',
      brief:
        'Trocando a segunda por RESTRICTIVE: agora ela só pode remover linhas que a permissiva liberou, nunca acrescentar.',
      sql: `reset role;
drop policy if exists nao_confidencial on relatorios;
create policy nao_confidencial on relatorios
  as restrictive
  for select to app_funcionario
  using (confidencial = false);
set role app_funcionario;
select id, titulo from relatorios order by id;`,
      expect:
        'Só o relatório não confidencial de vendas: a política restritiva exige confidencial = false por cima do que a permissiva já filtrou por departamento.',
      rows: 1,
      concept: {
        text: 'Uma política RESTRICTIVE se combina com AND: uma linha só é visível se passar por pelo menos uma política permissiva e por todas as restritivas. É a forma de impor uma regra que nenhuma política permissiva pode driblar.',
        url: 'https://www.postgresql.org/docs/current/sql-createpolicy.html',
      },
    },
    {
      id: 'outro-departamento',
      title: 'A restrição vale para qualquer departamento',
      brief: 'Trocando de departamento, a mesma regra continua valendo: nunca confidencial.',
      sql: `set app.departamento = 'rh';
select id, titulo from relatorios order by id;`,
      expect:
        'Só o relatório não confidencial do RH. A política restritiva não menciona departamento — ela vale por cima de qualquer política permissiva que exista.',
      rows: 1,
      concept: {
        text: 'Uma política não precisa repetir a condição de outra para valer junto: RESTRICTIVE e PERMISSIVE são checadas independentemente e combinadas depois — AND entre os grupos, OR dentro do grupo permissivo.',
        url: 'https://www.postgresql.org/docs/current/ddl-rowsecurity.html',
      },
    },
  ],
  setup,
};
