import type { Lab } from '../lab.js';

const setup = `
create table documentos (
  id integer generated by default as identity primary key,
  tenant text not null,
  titulo text not null,
  corpo text not null
);

insert into documentos (tenant, titulo, corpo) values
  ('acme', 'Contrato 2026', 'Assinado em janeiro.'),
  ('acme', 'Ata do conselho', 'Reunião de fevereiro.'),
  ('globex', 'Plano de vendas', 'Meta do trimestre.'),
  ('globex', 'Salários', 'Confidencial.');

create role app_tenant nologin;
grant select, insert, update, delete on documentos to app_tenant;

-- A tabela pertence a uma role comum, não ao superusuário: RLS nunca se aplica a um
-- superusuário, e um lab que fingisse o contrário ensinaria errado.
create role app_dono nologin;
alter table documentos owner to app_dono;`;

/**
 * Multi-tenancy without RLS depends on every query remembering the WHERE. This lab moves
 * that rule into the database and then shows the three things people trip on: no policy
 * means no rows, the owner is exempt until forced, and reading is not writing.
 */
export const rowLevelSecurity: Lab = {
  id: 'row-level-security',
  title: 'Row-Level Security multi-tenant',
  summary:
    'Duas empresas na mesma tabela. Em vez de confiar que toda consulta lembre do WHERE tenant = ..., a regra passa a morar no banco.',
  level: 'avançado',
  panel: 'policies',
  premise:
    'A tabela documentos guarda dados de dois clientes, acme e globex. Hoje qualquer consulta que esqueça o filtro mostra tudo para todos. Vamos mover essa regra para dentro do banco e testá-la assumindo a role da aplicação.',
  steps: [
    {
      id: 'sem-rls',
      title: 'O problema',
      brief:
        'A role da aplicação já tem SELECT na tabela. Sem mais nada, ela vê os dois clientes — basta uma consulta sem WHERE.',
      sql: `set role app_tenant;
select id, tenant, titulo from documentos order by id;`,
      expect:
        'Quatro linhas, dos dois tenants. Um único endpoint que esqueça o filtro vaza o cliente inteiro.',
      rows: 4,
    },
    {
      id: 'ligar',
      title: 'Ligando row level security',
      brief: 'Com RLS ativo, o padrão do PostgreSQL é negar: sem política, nenhuma linha passa.',
      sql: `reset role;
alter table documentos enable row level security;
set role app_tenant;
select id, tenant, titulo from documentos order by id;`,
      expect:
        'Zero linhas, sem erro nenhum. É o "a consulta parou de retornar em produção" mais comum — e o motivo de o relatório de segurança avisar sobre RLS sem política.',
      rows: 0,
    },
    {
      id: 'politica',
      title: 'A política que devolve as linhas certas',
      brief:
        'A política compara a coluna com uma variável da sessão. Quem conecta declara o tenant uma vez; o banco aplica em toda consulta.',
      sql: `reset role;
drop policy if exists documentos_do_tenant on documentos;
create policy documentos_do_tenant on documentos
  for all to app_tenant
  using (tenant = current_setting('app.tenant', true))
  with check (tenant = current_setting('app.tenant', true));
set role app_tenant;
set app.tenant = 'acme';
select id, tenant, titulo from documentos order by id;`,
      expect:
        'Só as duas linhas da acme. Troque para globex e rode de novo: a consulta é a mesma, o resultado não.',
      rows: 2,
    },
    {
      id: 'escrita',
      title: 'Ler não é escrever',
      brief:
        'USING decide quais linhas existem para quem lê. WITH CHECK decide quais linhas podem ser gravadas — sem ele, dá para escrever no tenant do vizinho.',
      sql: `insert into documentos (tenant, titulo, corpo) values ('globex', 'Infiltrado', 'Não deveria entrar.');`,
      expect:
        'new row violates row-level security policy. O WITH CHECK recusa a linha antes de ela existir.',
      refused: '42501',
    },
    {
      id: 'dono',
      title: 'O dono passa por cima',
      brief:
        'A tabela pertence a app_dono. RLS não se aplica ao dono, por padrão — e em um banco onde a aplicação conecta como dono da tabela, isso anula a proteção inteira.',
      sql: `reset role;
set role app_dono;
select id, tenant, titulo from documentos order by id;`,
      expect:
        'Como dono, as quatro linhas voltam — a política continua lá, apenas não vale para ele.',
      rows: 4,
    },
    {
      id: 'forcar',
      title: 'Forçando para todos',
      brief:
        'FORCE ROW LEVEL SECURITY faz a política valer também para o dono. É o que transforma RLS em garantia em vez de convenção.',
      sql: `reset role;
alter table documentos force row level security;
set role app_dono;
select id, tenant, titulo from documentos order by id;`,
      expect:
        'Zero linhas para o dono também: a política é "to app_tenant", então para app_dono não existe política nenhuma — e com FORCE, nenhuma política significa nenhuma linha. Uma ressalva que vale mais que o lab: superusuário ignora RLS sempre, com ou sem FORCE. Se a aplicação conecta como superusuário, nada disso protege.',
      rows: 0,
    },
  ],
  setup,
};
