import type { Lab } from '../lab.js';

const setup = `
create table salarios (
  id integer generated by default as identity primary key,
  nome text not null,
  salario numeric(10, 2) not null
);

insert into salarios (nome, salario) values
  ('Ana Ribeiro', 8200.00),
  ('Bruno Alves', 6100.00),
  ('Carla Souza', 9750.00);`;

/**
 * A SECURITY DEFINER function runs with the privileges of who created it, not who calls
 * it — that is the whole point of granting EXECUTE without granting SELECT on the table
 * underneath. But an unqualified table name inside the function is resolved using the
 * *caller's* search_path unless the function pins its own — which is how the caller ends
 * up choosing what the "trusted" function actually reads.
 */
export const securityDefiner: Lab = {
  id: 'security-definer',
  title: 'SECURITY DEFINER e o search_path',
  summary:
    'Uma função pode ler o que quem a chama não pode ler — e, sem um search_path fixo, quem a chama pode escolher de qual tabela ela lê.',
  level: 'avançado',
  panel: 'privileges',
  premise:
    'A role leitor nunca vai receber SELECT em salarios. Em vez disso, ela vai receber EXECUTE numa função que calcula a média — a forma certa de expor um resultado sem expor a tabela. Vamos ver essa função funcionar, e depois ver o que falta nela para ser segura de verdade.',
  steps: [
    {
      id: 'criar-funcao',
      title: 'Uma função que sabe mais que quem a chama',
      brief:
        'SECURITY DEFINER faz a função rodar com o privilégio de quem a criou (aqui, o dono do banco), não de quem a chama.',
      sql: `do $$
begin
  if exists (select 1 from pg_roles where rolname = 'leitor') then
    revoke execute on function relatorio_medio() from leitor;
  end if;
end $$;
drop schema if exists leitor_area cascade;
drop role if exists leitor;
create role leitor nologin;
create schema if not exists leitor_area authorization leitor;
create or replace function relatorio_medio() returns numeric
  language sql security definer
  as $$ select avg(salario) from salarios $$;
grant execute on function relatorio_medio() to leitor;`,
      expect:
        'A matriz continua sem nenhuma marca para leitor em salarios — o que ela ganhou foi EXECUTE numa função, um privilégio que essa tabela não mostra.',
      concept: {
        text: 'Uma função SECURITY DEFINER executa com os privilégios de quem a definiu, não de quem a chama — o oposto do padrão SECURITY INVOKER. É assim que se expõe um resultado calculado sem expor a tabela por trás dele.',
        url: 'https://www.postgresql.org/docs/current/sql-createfunction.html',
      },
    },
    {
      id: 'negado-direto',
      title: 'Direto na tabela, continua negado',
      brief: 'EXECUTE na função não é SELECT na tabela — são privilégios diferentes.',
      sql: `set role leitor;
select * from salarios;`,
      expect: 'permission denied for table salarios. O acesso direto continua fechado.',
      refused: '42501',
      concept: {
        text: 'GRANT EXECUTE ON FUNCTION concede apenas o direito de chamar a função; não abre, por si só, nenhum privilégio sobre as tabelas que a função lê por dentro.',
        url: 'https://www.postgresql.org/docs/current/sql-grant.html',
      },
    },
    {
      id: 'via-funcao',
      title: 'Pela função, funciona',
      brief: 'Mesma role, mesma sessão — agora chamando a função em vez da tabela.',
      sql: `select relatorio_medio();`,
      expect:
        'Uma linha, com a média real dos três salários. A função alcançou o que leitor sozinho não alcança.',
      rows: 1,
      concept: {
        text: 'Dentro de uma função SECURITY DEFINER, cada referência à tabela é checada contra os privilégios do dono da função, não os de quem a chamou — por isso ela lê salarios mesmo sem leitor ter SELECT nela.',
        url: 'https://www.postgresql.org/docs/current/sql-createfunction.html',
      },
    },
    {
      id: 'sequestro-search-path',
      title: 'Sequestrando o search_path',
      brief:
        'A função escreveu apenas "salarios", sem esquema. Sem um search_path fixo, é o esquema atual de quem chama que decide qual "salarios" isso é — e leitor já é dono do próprio esquema, leitor_area.',
      sql: `set role leitor;
create table if not exists leitor_area.salarios (salario numeric);
delete from leitor_area.salarios;
insert into leitor_area.salarios values (999999);
set search_path to leitor_area, public;
select relatorio_medio();`,
      expect:
        'A "média" agora é 999999 — um número que não existe na tabela real. A função de confiança leu a tabela que leitor escolheu para ela, sem precisar de nenhum privilégio na tabela verdadeira.',
      rows: 1,
      concept: {
        text: 'Sem um search_path próprio, uma função resolve nomes não qualificados (como "salarios", sem esquema) usando o search_path da sessão de quem a chama — algo que o chamador controla livremente com SET search_path.',
        url: 'https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATH',
      },
    },
    {
      id: 'corrigir',
      title: 'Fixando o search_path da função',
      brief:
        'A correção não é revogar CREATE de leitor — é a função nunca depender do search_path de ninguém.',
      sql: `reset role;
create or replace function relatorio_medio() returns numeric
  language sql security definer
  set search_path = public
  as $$ select avg(salario) from salarios $$;
set role leitor;
select relatorio_medio();`,
      expect:
        'A média real volta, mesmo com o search_path de leitor ainda apontando primeiro para golpe. A função passou a ignorar o search_path de quem a chama.',
      rows: 1,
      concept: {
        text: 'CREATE FUNCTION ... SET search_path = ... prende um valor fixo de search_path só para a execução da função, independente do que a sessão que a chama tiver configurado — a defesa recomendada para toda função SECURITY DEFINER.',
        url: 'https://www.postgresql.org/docs/current/sql-createfunction.html',
      },
    },
  ],
  setup,
};
